### ISSUE TITLE
Add a Dockerfile

### ISSUE THREAD

**Issue by adrienbrault** [favll/pogom#100]
Hi,

I've been using https://github.com/PokemonGoMap/PokemonGo-Map , which was very easy to setup thanks to its out of the box docker support https://github.com/PokemonGoMap/PokemonGo-Map/blob/develop/Dockerfile .
I don't have to know anything about python to run it!

So it would be nice to have one on this project 😃

**Comment by Jordan-TE** [comment]
as i made One for another project, pogo iv renamer, i'll try to make one for this one ,let me 1 or 2 days before i make it i'll make a Pr as soon as i have something working and easy to setup

**Comment by nborrmann** [comment]
Has been added.
