### ISSUE TITLE
[Suggestion] Updates (while keeping data)

### ISSUE THREAD

**Issue by Lionir** [favll/pogom#101]
Could there be a command or a UI element on the webpage to automatically update the components from this github while keeping the data? (Accounts, Web Password, Stats)

**Comment by nborrmann** [comment]
Config is saved across sessions. But there's no way around restarting the server after a `git pull`.

**Comment by Lionir** [comment]
Well, If I clone this repo, the config would be replaced and data would be lost, no?

**Comment by favll** [comment]
Nope.

**Comment by Lionir** [comment]
@favll Could there a UI element to update the components and restart the server?
