### ISSUE TITLE
Question about accounts

### ISSUE THREAD

**Issue by kalimerre** [favll/pogom#104]
Hey,

Thanks for your tool (once again)
I got a little question
If I use https://github.com/FrostTheFox/ptc-acc-gen to generate account, do I need to validate each email to verify the account or if I don't do it the account will still be available and ready to use with the tool ?

**Comment by nborrmann** [comment]
Accounts work for two days without activating. After that you will get errors.

**Comment by kalimerre** [comment]
Ok so I need to activate
Do you have any tips/scripts to create account and activate it or I need to click each link ?

**Comment by Lionir** [comment]
@Kalimerre You could use a service like Throwawaymail.com and activated them using these fake accounts. I've used it and it works flawlessly.

**Comment by kalimerre** [comment]
Yeah yeah but lazy as I am, I wanted to have all accounts directly activated :D 
But thanks for the tips!
