### ISSUE TITLE
Can't see the actual map

### ISSUE THREAD

**Issue by Scarletterr** [favll/pogom#106]
I may be overlooking something. It lets me configure the map, but just keeps returning me to the configure page when I try to open the map. What am I doing wrong?

**Comment by Shalasere** [comment]
The map is actually located at localhost:5000. The config splashpage is localhost:5000/config

**Comment by Scarletterr** [comment]
Every time I type it in, it auto-directs me to localhost:5000/config

**Comment by Shalasere** [comment]
Hmm, does it prompt an error when clicking the submit button?

**Comment by Scarletterr** [comment]
Nope, it says the changes were successful. That's why I'm so confused lol

**Comment by nborrmann** [comment]
You need to add at least one account name and password, separated by a ':'.

**Comment by Scarletterr** [comment]
Lol I definitely forgot the ":" thank you so much
