### ISSUE TITLE
Curious if modification to the scan delay and manual threading configuation is possible.

### ISSUE THREAD

**Issue by Shalasere** [favll/pogom#107]
I know in a few of the other applications based off the new API still rely on commands to runserver.py and the -sd and -t flags can be modified manually to control the scan delay and threading respectively. While the threads are calculated via the workers in the scan_config file but would it be possible to implement this as a manual configuration from the web interface?

**Comment by nborrmann** [comment]
Our goal is to provide the best configuration ouof the box and not require the user to bother with it.
