### ISSUE TITLE
Error installing xxhash

### ISSUE THREAD

**Issue by Adiron147** [favll/pogom#116]
I got this error while trying to install xxhash:

Command "C:\Python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\0196~1\\appdata\\local\\temp\\pip-build-dt9yim\\xxhash\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\0196~1\appdata\local\temp\pip-pdfyfs-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\0196~1\appdata\local\temp\pip-build-dt9yim\xxhash\

I tried installing this:
https://www.microsoft.com/en-us/download/details.aspx?id=44266
but it didn't helped.

Can you help me please?

**Comment by MutanGFX** [comment]
Same thing, can't install xxhash

**Comment by Adiron147** [comment]
I got it.
I don't know if it's related, but I my profile name in windows was in hebrew.
I changed it to english, restarted, uninstalled the c++ compiler for windows, installed it again and it worked.
Maybe this could help to other users as well.

**Comment by MutanGFX** [comment]
Well... I really don't think it's going to help me lol

**Comment by ObviousLeeGitHub** [comment]
Install this: https://www.microsoft.com/en-us/download/details.aspx?id=44266
Then try to install xxhash again. Worked for me.

**Comment by SysQo** [comment]
Either install C Compiler for python (if using windows), or make sure you have GCC and a development branch of python installed if you are building on a linux server!

**Comment by kara71** [comment]
For linux users, the command is 
`sudo apt-get install python-dev`
as mentioned by @SysQo

**Comment by KikkomanChow** [comment]
This needs to be part of the instructions. 
https://www.microsoft.com/en-us/download/details.aspx?id=44266
works perfectly after this.

**Comment by SysQo** [comment]
@kara71 Please note that is Ubuntu only. If he were using RHEL (like I use) he would be using `yum install python-devel`

**Comment by favll** [comment]
This seems to have resolved itself?
