### ISSUE TITLE
Accounts logging out after a while

### ISSUE THREAD

**Issue by Gabboplano** [favll/pogom#119]
So it seems that after 2-3 hours of scanning, some accounts log out (I think?) never to log back in again, causing slowdowns in the scans.
Basically, my cmd is spammed with PTC user login for: xxxxx, PTC login successful but it never requests/acquires access tokens for the account
Is there a fix for this or even just a script to close and rerun the server every 2 hours?
(I use 130 accounts to scan a 2km radius area)

**Comment by lax20attack** [comment]
If you are windows, you can always run a scheduled task to kill a program and restart it.

**Comment by Gabboplano** [comment]
yeah I just did that, thanks
but is there a reason why this happens? too many accounts or something?

**Comment by nborrmann** [comment]
>it never requests/acquires access tokens for the account

How do you know? It doesn't log any output when doing that.
