### ISSUE TITLE
Efficiency is weak

### ISSUE THREAD

**Issue by khag7** [favll/pogom#125]
Could we implement some of these ideas:
https://www.reddit.com/r/pokemongodev/comments/4wqkeg/efficient_server_sparing_scanning/

The basic idea is to cache spawn points. We know they spawn hourly, so we just need to full scan for an hour to completely map the spawnpoints in an area. Then we can scan even faster by scanning only the necessary spawn points during any given minute.

**Comment by Lionir** [comment]
Well, the scanning goes quite fast but using spawnspoints could make you miss pokemons.

**Comment by ShutUpPetey** [comment]
Also the number of spawn points in a decently populated area is far more than the number of location a scanner like this uses. Also as a rural user, I find that new spots pop up about once a week.

**Comment by khag7** [comment]
I guess I'm thinking about the "bigger picture". The truth is Niantic is going to keep fighting back as long as we are spamming their server with a ridiculously large number of requests. If we created a map of spawnpoints we would have that information forever, without the need for constantly bombarding their API. If we can ease up on requests, they'll stop fighting us.

Probably once a day you'd want to re-scan your area for new spawn points. That should take 1 hour. the other 23 hrs of the day you would only need to make a small fraction of the requests we're currently making. There's a couple other projects doing that already, but none as good as this one. Its a feature that every dev should be aiming for. A script like this which only relies on constant requests and makes no effort to improve in efficiency will get a C&D sooner than an app which limits server requests by caching. Read that reddit post I linked, that guy has the right idea and already released a script that does those things, but its not bundled with any map or notifications.

**Comment by Lionir** [comment]
@kag7 Every project which uses the API is bound to be C&D, that we make tons of request or not. I do get that you think this might be better but it's not because it will miss Pokemon's and the number of spawnpoints could create more requests than what we are doing depending on the location you are scanning. Urban areas have dozens and dozens of spawnpoints which would make it less efficient.

**Comment by nborrmann** [comment]
#199
