### ISSUE TITLE
not displaying pokemons from lured pokestops?

### ISSUE THREAD

**Issue by bowenshu** [favll/pogom#127]
It seems that the spawns from lured pokestops are not displaying on the map? Has anyone else seen this issue too?

**Comment by YonderGod** [comment]
Aren't lured pokemon different for everyone? If I'm not wrong, then this is intentional.

**Comment by bowenshu** [comment]
if the Pokemon comes from incense then it's only for the individual that used incense. Lured pokemons at stops are the same for everyone (but their despawn time is much shorter than naturally spawned pokemons

**Comment by Chris221** [comment]
Dupe #13
