### ISSUE TITLE
Nothing happens 

### ISSUE THREAD

**Issue by sunkillerqc** [favll/pogom#129]
$ python runserver.py
 [     pgoapi] [   INFO] pgoapi v1.1.7 - Copyright (c) 2016 tjado <https://github.com/tejado>

His writing it and nothing happens

**Comment by TheMaskedMonkey** [comment]
Go to https://localhost:5000/

**Comment by sunkillerqc** [comment]
This site can not provide a secure connection

localhost sent an incorrect answer.

**Comment by TheMaskedMonkey** [comment]
er, try this instead. My bad: http://127.0.0.1:5000/

**Comment by sunkillerqc** [comment]
This site is inaccessible

localhost does not allow the connection.
Do a Google search on localhost 5000.
ERR_CONNECTION_REFUSED


And console close for no error

**Comment by sunkillerqc** [comment]
I close and restart and now work 0.0 

Ty for you help TheMaskedMonkey xD
