### ISSUE TITLE
I got this Error, please help me

### ISSUE THREAD

**Issue by rzkingaioria** [favll/pogom#131]
http://prnt.sc/c3ciyy

**Comment by niayh** [comment]
I encountered this earlier with accounts I had just created. I saw a previous post from one of the devs claiming that they do a ToS check and accept if necessary; however, when I signed into one of the accounts I was using, the ToS popped up. That said, I'm not entirely sure the ToS check is functioning in this project at the moment

**Comment by favll** [comment]
Duplicate of #123
