### ISSUE TITLE
[Suggestion] More threads

### ISSUE THREAD

**Issue by TheMaskedMonkey** [favll/pogom#133]
Would it be possible to have more threads which can also be based on location?
I have 19 accounts and around 10 locations. This has created a total of 3 threads and the scan is very slow. I'm not sure if this on Niantic's end or just because there's 3 threads.

I do feel that increasing the threads would be a much needed improvement for scanning.

**Comment by YonderGod** [comment]
I don't fully understand how this works or why these are the values, but I'm looking through the code and learning as I go.
from scan.py:
`num_workers = max(int(math.ceil(len(config['ACCOUNTS']) / 23.0)), 3)`

So, the number of threads is equal to your number of accounts divided by 23(rounded up), with a minimum value of 3. 
You could try changing this and see what happens. Have some fun, learn some code.

**Comment by TheMaskedMonkey** [comment]
Yeah, I've already swooped through it. Experimented with 20 threads and found it just increases the speed it loads accounts and not actual scan time.

**Comment by YonderGod** [comment]
Keep in mind that each account can only scan a 70 meter radius every 10 seconds. It might not be possible to go faster, without missing some pokemon.

**Comment by TheMaskedMonkey** [comment]
But it only does one location at a time which makes me believe it's something to do with pogom and not Niantic.

**Comment by TheMaskedMonkey** [comment]
It doesn't scan multiple locations at once
Like if you had 1 account, sure. Scan one at a time. Makes sense
But if you have 20 accounts with 10 locations. It still does it one at a time.

I feel like that could be improved a bit.

**Comment by nborrmann** [comment]
You're bottlnecked by the number of accounts. It can do one scan every ten seconds on each thread. Adding more threads won't help.

As for the different locations, it does scan all of them successively. When its finished with the first, it will jump to the next. Have you waited long enough for the first location to finish scanning?

We could randomly scan locations, but I don't see how this would improve anything.

**Comment by nborrmann** [comment]
Also see the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)

**Comment by TheMaskedMonkey** [comment]
> When its finished with the first, it will jump to the next.

Why not just do multiple locations at once if you have enough accounts to handle it? @nborrmann
