### ISSUE TITLE
Problème page configuration 

### ISSUE THREAD

**Issue by Tagada22** [favll/pogom#135]
hello , maybe somebody can help me :)

 i have a problems with thé configuration 

the instalaltion was good, when i open http://xxx.x.xx.xx/5000

its open pokemon go map config , i enter my informations and said me config has saved

http://prntscr.com/c39av3

but when i re open my vps:5000 the page rest in config , same problem when i stop the script and re laucnh it .

**Comment by YonderGod** [comment]
It doesn't look like you entered any accounts.

**Comment by Tagada22** [comment]
Yes i have entered account like that 

Username1:password1Username2:password2Username3:password......

**Comment by nborrmann** [comment]
One user:password per line please.
