### ISSUE TITLE
Web Page not Found

### ISSUE THREAD

**Issue by crob203** [favll/pogom#137]
Sorry if his is a very stupid question - im not a coder so it probably is.
I followed all the installation steps but when I point my browser to 127.0.0.1:5001 it just goes to web page not found. I am on OSX using terminal and all the installation steps seemed to go fine. The only bit I am unsure on is that when I start the server the terminal just hangs; I put the -H "127.0.0.1" -P 5001 in at this stage but get no messages that may indicate success or failure.

Chriss-MacBook-Pro:pogom CJR$ python runserver.py
2016-08-08 22:25:46,758 [     pgoapi] [   INFO] pgoapi v1.1.7 - Copyright (c) 2016 tjado <https://github.com/tejado>
-H "127.0.0.1" -P 5001

Thanks in advance.

Chris

**Comment by crob203** [comment]
Sorry, I am being thick got it!

**Comment by nakami** [comment]
please write down the solution you came up with to help others. thank you.
