### ISSUE TITLE
[Question] What is Status Code 3?

### ISSUE THREAD

**Issue by Lionir** [favll/pogom#139]
An Account, (I don't which since there's no way to tell), gets Status Code 3. What does it mean? (Sorry if this seems stupid)

**Comment by SysQo** [comment]
the TOS has not been accepted on that account. This application is supposed to have a script that automatically accepts TOS on all PTC accounts but i dont think it is working properly.

Please make sure you have accepted the TOS on all of your accounts, and close this Issue

**Comment by favll** [comment]
Duplicate of #123

**Comment by Lionir** [comment]
@SusQo Do you know of any tool which could go through all my accounts and accept the TOS if it wasn't done?
