### ISSUE TITLE
[Suggestion] Would be nice to colour code the map coverage

### ISSUE THREAD

**Issue by mhenley-uk** [favll/pogom#142]
It would be nice to colour code the map coverage circles based on the last time a full scan was run...

Green = < 5 minutes
Orange = 5 minutes > 15 minutes
Red = > 15 Minutes

Not sure on the brackets but would be good to indicate on the UI...especially when running multiple accounts with multiple locations.

**Comment by nborrmann** [comment]
Problem is, we're not displaying the individual scan locations. So there can be one location which was scanned just now and another that hasn't been scanned in minutes, all in the same circle.

If we display all 70m circles, the map gets extremely laggy, so we didn't do that.

**Comment by mhenley-uk** [comment]
Sorry, by map coverage I don't mean the multiple circles within the radius that make up a "beehive" Instead I meant the circles that define the radius you want to scan. When you have multiple scan locations its quite hard to see which one is currently active. 

![Example with two scan circles](https://cloud.githubusercontent.com/assets/1723176/17482369/bf3df2b2-5d81-11e6-904e-edfd496702dc.png)

...for example in the embedded image we see two scan circles with different radius's...on the UI we don't know which one is currently active as part of the scan process.
