### ISSUE TITLE
Scans

### ISSUE THREAD

**Issue by ijcarson1** [favll/pogom#155]
https://gyazo.com/d3367be362101dc8ce740eb9760849ed

Not getting any errors (the 2 that show are when i click stats - 400)

Any idea why it's not showing all the accounts I have added which is 10. Also, why is it not scanning/how do I make it scan? I previously tried 1 and multiple locations at 300m per location, but didn't do anything

**Comment by nborrmann** [comment]
Please get the latest version from github and post your command line output.

**Comment by ijcarson1** [comment]
https://gyazo.com/d48b22a6dc79f918597ba2bc641b36d8

**Comment by ijcarson1** [comment]
Ahh, restarted runserver, and the accounts logged in. My bad
