### ISSUE TITLE
set_cover() slowing down script init tremendously when a large radius is set.

### ISSUE THREAD

**Issue by karololszak** [favll/pogom#16]
1. Set a radius of >10k.
2. Start the script.
3. Wait...... wait longer... 

It is just annoyingly slow. Everything in this repo seems stripped down and optimised in comparison to the original repo, while the set_cover function - which seems to be added to the org. code - is just really slow. I guess it's the double for loop's fault and possibly the Geodesic methods?

Ideas to consider: a switch for a less-precise method of calculating the points? 

Why it bothers me: I wanted to crawl large areas overnight...

**Comment by nborrmann** [comment]
You're right, I profiled the function:
```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.034    0.034   19.273   19.273 <string>:1(<module>)
        1    0.255    0.255   19.239   19.239 /pogom\pogom\search.py:28(set_cover)
    54270    0.323    0.000   12.237    0.000 C:\python27\lib\site-packages\geographiclib\geodesic.py:1012(Inverse)
    54270    1.294    0.000   11.557    0.000 C:\python27\lib\site-packages\geographiclib\geodesic.py:703(_GenInverse)
   108117    0.999    0.000    7.232    0.000 C:\python27\lib\site-packages\geographiclib\geodesic.py:627(_Lambda12)
    54270    0.273    0.000    6.735    0.000 C:\python27\lib\site-packages\geographiclib\geodesic.py:1063(Direct)
    54270    0.277    0.000    6.351    0.000 C:\python27\lib\site-packages\geographiclib\geodesic.py:1055(_GenDirect)
   162387    0.923    0.000    5.406    0.000 C:\python27\lib\site-packages\geographiclib\geodesic.py:429(_Lengths)
    54270    1.323    0.000    4.451    0.000 C:\python27\lib\site-packages\geographiclib\geodesicline.py:66(__init__)
  3575236    2.747    0.000    2.747    0.000 C:\python27\lib\site-packages\geographiclib\geomath.py:106(polyval)
```
Most time is spent in the `Inverse` and `Direct` functions. Maybe there are faster alternatives.

I don't see a possibility for unrolling the loops though. If there are 54k single circles in the cover, we need to calculate them all.

**Comment by karololszak** [comment]
Can we do a cache of them then? Like a file-stored cache, so when I run the script for the same location it would just use the previously calculated values.

**Comment by nborrmann** [comment]
That's the definition of bloat.
