### ISSUE TITLE
Possible to use google accounts?

### ISSUE THREAD

**Issue by CakeHole83** [favll/pogom#165]
## Checklist
 - [ ] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [ ] I have checked if this issue already exists (both open and closed issues)
 - [ ] I am using the most recent version of pogom from the master branch
 - [ ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ ] I'm posting the complete log
 - [ ] I'm using a descriptive title for this issue

## My Issue
Is it possible to use your google accounts? Remaking 30 accounts in PTC is horrific.
...

**Comment by NHLGames** [comment]
There are scripts to automate PTC account creation, you just have to look ;)

**Comment by nborrmann** [comment]
Where are you getting 30 google accounts? xD

**Comment by EiTeR94** [comment]
type on google : ptc gen account

and take the first one, easy to use.

**Comment by throwpigeyaway** [comment]
^ is there a ptc gen account that runs on mac ? i've been using http://goplaypkmn.xyz/ but its been kinda slow.

**Comment by Baklap4** [comment]
It is possible to use google accounts just add write this down into the config.json in the accounts block:

```
{
       	"username":"username",
       	"password":"password",
       	"provider":"google"
},
```

**Comment by nborrmann** [comment]
Thanks @Baklap4 for the explanation.

Google accounts are kinda supported, but can't be added through the web gui. I don't really think this is necessary. You need tons of accounts and PTC accs are way easier to create than google accounts.
