### ISSUE TITLE
Cannot delete location

### ISSUE THREAD

**Issue by NHLGames** [favll/pogom#166]
I cannot seem to delete a location.  When I click the delete button, it disappears for a few seconds but then reappears on the map.  Now it seems I am doing concurrent scans.  I have to edit config.json to fully remove it.

**Comment by nborrmann** [comment]
Make sure you are logged in. F5 on the map and look at the first label in the side bar.

**Comment by NHLGames** [comment]
Oh i'm definitely logged in, without being authenticated it doesn't even give me the option to delete.

**Comment by nborrmann** [comment]
Sometimes the client thinks it is logged in, even though it isn't. Then the server will just drop all requests to change the location. Hit F5 update the client.

**Comment by djv2** [comment]
try deleting the db?

**Comment by NHLGames** [comment]
Tried deleting the db.  But it seems the locations are actually stored in the config.json file.

Found a (strange) workaround: Deleting it from mobile seems to work?

**Comment by szeco** [comment]
@NHLGames You can login again by going to _/config_ and entering your password. When you go back to maps you should be able to add/delete locations again.

**Comment by favll** [comment]
Not-reproducible -> Closed :( If this should happen to other users we will investigate this further.
