### ISSUE TITLE
Cannot kill server

### ISSUE THREAD

**Issue by NHLGames** [favll/pogom#167]
Hitting Control + Z does not seem to terminate the server properly.  When I attempt to restart it, it says address is in use.  Killing the python process does nothing (even as superuser) and I have to restart my VM to get rid of it.  Is the process running with some sort of elevated privileges?

**Comment by r3pek** [comment]
use kill -9 <pid>

**Comment by djv2** [comment]
ctrl + c for windows

**Comment by DavidBindloss** [comment]
CTRL+Z puts a task into the background in your terminal, so the process is still running in the background. If you want to get it back again you can type:

`$ fg`

And it will pull the process back into the foreground. If you want to kill the task completely, you need to kill it on Terminal with

`$ sudo kill -9 <INSERT PID OF python runserver.py HERE>`

Hope that clears things up for you.
