### ISSUE TITLE
Can't Add Location on Mobile

### ISSUE THREAD

**Issue by jcady** [favll/pogom#175]
## Checklist
 - [X] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [X] I have checked if this issue already exists (both open and closed issues)
 - [X] I am using the most recent version of pogom from the master branch
 - [X] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [X] I'm posting the complete log
 - [X] I'm using a descriptive title for this issue

## My Issue

On both iOS and Android it seems like you can't "click" the map to add a location. Am I doing it wrong? :)

...

**Comment by Lionir** [comment]
@jcady I can confirm that it works. Are you authenticated/logged on your device?

**Comment by jcady** [comment]
D'oh, that was it. Much appreciated!
