### ISSUE TITLE
Error in worker thread. Returning empty response. Error: local variable 'r' referenced before assignment

### ISSUE THREAD

**Issue by gwydre** [favll/pogom#178]
## Checklist
 - [x] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [x] I have checked if this issue already exists (both open and closed issues)
 - [x] I am using the most recent version of pogom from the master branch
 - [x] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [x] I'm posting the complete log
 - [x] I'm using a descriptive title for this issue

## My Issue
i keep getting this error

2016-08-09 22:32:20,855 [   auth_ptc] [  ERROR] PTC Login failed.
2016-08-09 22:32:20,859 [     pgoapi] [  ERROR] Error in worker thread. Returning empty response. Error: local variable 'r' referenced before assignment
2016-08-09 22:32:20,860 [       scan] [   INFO] Map Download failed. Trying again.

...

**Comment by Ericyeah** [comment]
As stated in the FAQ, these errors are expected occasionally as Niantic's servers are still pretty unreliable.( the application is written to reissue the request)In the future please refrain from asking questions which are already answered.
