### ISSUE TITLE
always says "[       scan] [   INFO] Completed  0.00% of scan." but it is actually progressing

### ISSUE THREAD

**Issue by djv2** [favll/pogom#181]
see screenshot. however, it IS scanning & progressing
![2](https://cloud.githubusercontent.com/assets/20608679/17536512/0392c9ea-5e5b-11e6-8280-95c425b0ad33.jpg)

**Comment by nborrmann** [comment]
The error is in here:

```
            if ScanMetrics.NUM_STEPS:
                ScanMetrics.CURRENT_SCAN_PERCENT = float(ScanMetrics.STEPS_COMPLETED) / ScanMetrics.NUM_STEPS * 100
            else:
                ScanMetrics.CURRENT_SCAN_PERCENT = 0
```
NUM_STEPS is 0 somehow for you. Restarting the server will probably fix this.

**Comment by djv2** [comment]
sometimes restarting fixes it, sometimes it doesn't. usually after restart, the first scan has this problem. any consecutive scan is correct.

**Comment by nborrmann** [comment]
Closing this because it's a really minor issue.
