### ISSUE TITLE
Only empty but valid responses

### ISSUE THREAD

**Issue by ithr0n** [favll/pogom#182]
## Checklist
 - [x] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [x] I have checked if this issue already exists (both open and closed issues)
 - [x] I am using the most recent version of pogom from the master branch
 - [x] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [x] I'm posting the complete log
 - [x] I'm using a descriptive title for this issue

## My Issue
The map was working correctly with 40 accounts but meanwhile I only get those messages in the console:

> 
> 2016-08-10 01:18:59,431 [       scan] [   INFO] Completed 15.49% of scan.
> 2016-08-10 01:18:59,523 [     models] [WARNING] Received valid response but without any data. Possibly rate-limited?
> 2016-08-10 01:18:59,523 [       scan] [   INFO] Completed 15.50% of scan.
> 2016-08-10 01:18:59,572 [     models] [WARNING] Received valid response but without any data. Possibly rate-limited?
> 2016-08-10 01:18:59,572 [       scan] [   INFO] Completed 15.52% of scan.
> 2016-08-10 01:18:59,691 [     models] [WARNING] Received valid response but without any data. Possibly rate-limited?
> 2016-08-10 01:18:59,691 [       scan] [   INFO] Completed 15.53% of scan.
> 2016-08-10 01:18:59,770 [     models] [WARNING] Received valid response but without any data. Possibly rate-limited?
> 2016-08-10 01:18:59,770 [       scan] [   INFO] Completed 15.54% of scan.
> 2016-08-10 01:18:59,842 [     models] [WARNING] Received valid response but without any data. Possibly rate-limited?
> 2016-08-10 01:18:59,842 [       scan] [   INFO] Completed 15.55% of scan.
> 2016-08-10 01:18:59,936 [     models] [WARNING] Received valid response but without any data. Possibly rate-limited?
> 2016-08-10 01:18:59,937 [       scan] [   INFO] Completed 15.56% of scan.
> 2016-08-10 01:18:59,961 [     models] [WARNING] Received valid response but without any data. Possibly rate-limited?
> 2016-08-10 01:18:59,961 [       scan] [   INFO] Completed 15.57% of scan.
> 2016-08-10 01:19:00,065 [     models] [WARNING] Received valid response but without any data. Possibly rate-limited?
> 2016-08-10 01:19:00,065 [       scan] [   INFO] Completed 15.58% of scan.
> 2016-08-10 01:19:00,094 [     models] [WARNING] Received valid response but without any data. Possibly rate-limited?
> 2016-08-10 01:19:00,095 [       scan] [   INFO] Completed 15.59% of scan.
> 2016-08-10 01:19:00,209 [     models] [WARNING] Received valid response but without any data. Possibly rate-limited?
> 2016-08-10 01:19:00,210 [       scan] [   INFO] Completed 15.61% of scan.
> 2016-08-10 01:19:00,230 [     models] [WARNING] Received valid response but without any data. Possibly rate-limited?
> 2016-08-10 01:19:00,230 [       scan] [   INFO] Completed 15.62% of scan.
> 2016-08-10 01:19:00,516 [     models] [WARNING] Received valid response but without any data. Possibly rate-limited?
> 2016-08-10 01:19:00,517 [       scan] [   INFO] Completed 15.63% of scan.
> 2016-08-10 01:19:00,710 [     models] [WARNING] Received valid response but without any data. Possibly rate-limited?
> 2016-08-10 01:19:00,710 [       scan] [   INFO] Completed 15.64% of scan.
> 2016-08-10 01:19:01,176 [     models] [WARNING] Received valid response but without any data. Possibly rate-limited?
> 2016-08-10 01:19:01,177 [       scan] [   INFO] Completed 15.65% of scan.
> 2016-08-10 01:19:01,492 [     models] [WARNING] Received valid response but without any data. Possibly rate-limited?
> 2016-08-10 01:19:01,492 [       scan] [   INFO] Completed 15.66% of scan.
> 2016-08-10 01:19:02,059 [     models] [WARNING] Received valid response but without any data. Possibly rate-limited?
> 2016-08-10 01:19:02,059 [       scan] [   INFO] Completed 15.67% of scan.
> 2016-08-10 01:19:03,151 [     models] [WARNING] Received valid response but without any data. Possibly rate-limited?
> 2016-08-10 01:19:03,151 [       scan] [   INFO] Completed 15.68% of scan.
> 2016-08-10 01:19:03,563 [     models] [WARNING] Received valid response but without any data. Possibly rate-limited?
> 2016-08-10 01:19:03,565 [       scan] [   INFO] Completed 15.70% of scan.
> 2016-08-10 01:19:04,290 [     models] [WARNING] Received valid response but without any data. Possibly rate-limited?
> 2016-08-10 01:19:04,290 [       scan] [   INFO] Completed 15.71% of scan.
> 2016-08-10 01:19:05,743 [     models] [WARNING] Received valid response but without any data. Possibly rate-limited?
> 2016-08-10 01:19:05,743 [       scan] [   INFO] Completed 15.72% of scan.
> 2016-08-10 01:19:06,456 [     models] [WARNING] Received valid response but without any data. Possibly rate-limited?
> 2016-08-10 01:19:06,457 [       scan] [   INFO] Completed 15.73% of scan.
> 2016-08-10 01:19:06,536 [     models] [WARNING] Received valid response but without any data. Possibly rate-limited?
> 2016-08-10 01:19:06,536 [       scan] [   INFO] Completed 15.74% of scan.
> 

Do I need to take care about that?

**Comment by M0pp0r** [comment]
I have the same problem.
Updated to the newest verison and now I have this error.

**Comment by phantomvamp** [comment]
View issue 152 on this warning message. There is a lot more info on it.

**Comment by M0pp0r** [comment]
@phantomvamp thanks for that, i posted a reply since i dont seem to get less pokemon even with a lot of errors

**Comment by nborrmann** [comment]
Duplicate.
