### ISSUE TITLE
Enhancement: Push notifications for defined Pokemon. 

### ISSUE THREAD

**Issue by poloka** [favll/pogom#186]
As a functional user of the application, would like the ability to identify specific Pokemon I'm am looking for, so that upon spawning in searched areas the user receives a notification of a new spawning of a given Pokemon.

**Comment by YonderGod** [comment]
read the FAQ, it's already on the to:do list

**Comment by nborrmann** [comment]
Duplicate. 

Also: THE CHECKLIST ISNT THERE FOR SHITS AND GIGGLES!
