### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by omidzargham** [favll/pogom#19]
I am trying to use Ngrok to expose my localhost:5000 to the web, and this is working fine on my PC localhost, but it wont display the map on the ngrok public address. I can access the settings but it says "not authenticated, no scans yet, no full scan yet" even though it says logged in, sleeping, last full scan... on my pc. Is this supposed to be compatible with ngrok?

**Comment by nborrmann** [comment]
It's a javascript issue. Can you post the js console log?

**Comment by softlol** [comment]
Hi there, I have this error too - here is tha java script console https://gyazo.com/49d322d0a99883524757b2a2d97c0c0f

**Comment by nborrmann** [comment]
Whats happens if you access localhost:5000/static/map.js directly?
What's the output of the cmd console?

**Comment by softlol** [comment]
Internal server error
https://gyazo.com/c0237756d6695cfdb25a003d6520300a

**Comment by omidzargham** [comment]
So the ngrok address works on my PC, but the inability to see the map as I described was on my iphone. I can't get the JS console from safari on the iphone right now, but i'll try in a few hours. I have attached what I see when I put localhost:5000/static/map.js on my pc where the program is running
![hmm](https://cloud.githubusercontent.com/assets/7988750/17159239/a7423ba4-5350-11e6-8063-704165009745.PNG)

**Comment by omidzargham** [comment]
I don't get any output on the chrome js console or the command prompt when i did the localhost:5000/static/map.js

**Comment by Splashganger** [comment]
got the same error, Pokemon dont show up on the map, but i can see them in stats.
java script console says:
TypeError: document.getElementById(...) is null
 map.js:488:1
TypeError: google.maps.places is undefined
 map.js:128:9

**Comment by destroyerco** [comment]
I had a javascript error too while trying to load the map, the problem was that I missed to add the Google maps Api key to /pogom/__init__.py

**Comment by omidzargham** [comment]
@favll @nborrmann I found what was causing the error on my iphone, I got the JS console on the iphone and it says this:
"SyntaxError: Unexpected use of reserved word 'let' in strict mode
map.js:2"
So the problem is with the let statement on that 2nd line in map.js, you guys know better but I guess that's not compatible with mobile safari. Its not working on the chrome app on my iphone either.

**Comment by nborrmann** [comment]
Should be fixed in ea72e2c24e1b5c53cacf37a7aeb68087eb9b0583. Please comment if it still doesn't work. Closing this for now.
