### ISSUE TITLE
IP Banned

### ISSUE THREAD

**Issue by dudeman999** [favll/pogom#190]
I just set up the scanner, and the thing is/was awesome!!!! I had 130 accounts running a scan around my entire neighborhood and had a port forwarded so i could access the tracker on the go. 

Bummer news is, that I kept getting the "Received valid response but without any data. Possibly rate-limited?" message at each % update. I stopped the program due to no new pokemon appearing on the map. I tried on of the 130 accounts on a different map scanner and no pokemon showed up.

I just hopped on my legit account on my phone and no pokemon or pokestops showed up.
I turned off my wifi and connectedto 4g from my legit account and everything is back to normal.

This means my IP was banned (either soft or perma)!

SO HEADS UP!!!!

Also I'm open to more info how to fix this.

**Comment by compuguy** [comment]
I think the documentation should be ammended that this app should be run on an external server (i.e. not your home network). @dudeman999

**Comment by dudeman999** [comment]
@compuguy Yes most likely!!! It would save people from the same fate.

**Comment by TheUrbanNinja** [comment]
It's only a temp ban, only lasts like 15-20 mins...

**Comment by dudeman999** [comment]
@TheUrbanNinja Yes, I just discovered this. Im trying to determine the best way to avoid this then. Is there one???

**Comment by EiTeR94** [comment]
Try to use only 30-40accounts max with a min scan delay 7-9 random

**Comment by VergaraF** [comment]
You may use a proxy if you're running this server in your local network

**Comment by NWest707** [comment]
So my scanner isnt showing any pokemon despite it working fine earlier today.  I waited a few hours incase it was a soft ip ban and still nothing showing yet no errors.  My main account on my phone on say wifi shows pokemon so i dont think its ip.  Any ideas?

**Comment by nborrmann** [comment]
Duplicate.

**Comment by compuguy** [comment]
@EiTeR94 In that case, the user config frontend should be tweaked to allow a scan delay to be set, as well as spacing between logins.
