### ISSUE TITLE
Which ports need to be open?

### ISSUE THREAD

**Issue by trippyhat** [favll/pogom#193]
I have a default ip table rule that denies any outgoing traffic except on specific ports (ie, 80). When I run this, I can't log into PTC or get any map downloads (which I guess is from geopy's geocoder). 

Which ports do I have to open to get this to run?

**Comment by peacefulreason** [comment]
Set by the -P switch. Default is 5000.

**Comment by trippyhat** [comment]
@peacefulreason I opened up 5000, both outgoing and incoming. But this does not help with the PTC login failures and the geocoding failures.

**Comment by peacefulreason** [comment]
@trippyhat Sorry, I misunderstood. Wireshark indicates a source locally of the 52XXX range and a destination of 443. I don't see much traffic outside of that, but it's a lot of data to sift through with so many accounts.

**Comment by trippyhat** [comment]
@peacefulreason Hm, here are the ports I've opened: 80, 443, 5000, 22

But I'm still having the same issues.

**Comment by lax20attack** [comment]
runserver.py -H "0.0.0.0" -P 5000

Port forward to Port 5000.

**Comment by peacefulreason** [comment]
@trippyhat You have 22 open externally? If so you might reconsider exposing SSH to the internet. I don't think 80 is necessary here. You should have 443 and 5000 allowed in their respective directions. Also is it possible you're disallowing DNS lookup on UDP 53? If you can't resolve the hostnames for SSO and the API, that could also cause an issue.

**Comment by nborrmann** [comment]
For scanning the Niantic API, you need outgoing connections. Typically a router allows all outgoing connections. Especially to 80/443. Otherwise browser wouldn't work.
