### ISSUE TITLE
[Improvement] Add an option to hide pokemons on the server side

### ISSUE THREAD

**Issue by Faskill** [favll/pogom#208]
Hello,

I know this has already been asked, but the issue has been closed because this has been considered useless...
I'm using ngrok to tunnel my pogom to an iphone, and it is almost impossible to filter all the pokemons correctly and takes a really long while.. 

Unless it is very difficult to implement, shouldnt it be possible to only parse pokemons of a certain species on the map, that can then be consulted through the internet, or at least to add an option on the configuration page that hidden pokemons affect all users?

Thanks in advance !

**Comment by nborrmann** [comment]
![image](https://cloud.githubusercontent.com/assets/1723176/17560614/033f0d8c-5f23-11e6-8bdf-6388e5ed80ee.png)
