### ISSUE TITLE
Repeat notification of pokemon & Changing Despawn time

### ISSUE THREAD

**Issue by EternisRequiem** [favll/pogom#213]
## Checklist
 - [ x] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [x ] I have checked if this issue already exists (both open and closed issues)
 - [ x] I am using the most recent version of pogom from the master branch
 - [na] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ ] I'm posting the complete log
 - [x ] I'm using a descriptive title for this issue

## My Issue
I kept getting re-notified when I had a notification on for Dratini.
It originally stated it was going to despawn at 14:00, but I received 3-4 more notifications after a period of 3-4 minutes, and the same Dratini would pop up again and again, and it would shift the despawn timer from :00 to :04~ 0:06 and :09.  It would essentially say it would despawn in about 1-2 minutes later than the last time it reported.

Unsure how to submit any sort of log with this.  If it happens again I can try and reproduce the information.
...

**Comment by nborrmann** [comment]
Getting this as well. Dunno why. Shouldnt be happening.

**Comment by gwydre** [comment]
Same issue here some off the notifications keep coming back and timer gets changes Windows/Google Chrome

**Comment by Rutig** [comment]
Same here, also Windows/Google Chrome.

**Comment by nborrmann** [comment]
Should be fixed in 08164c0857d5d5af5db7bffb92e5442f47ced84d.
