### ISSUE TITLE
IP soft banned?

### ISSUE THREAD

**Issue by Mickey32111** [favll/pogom#214]
## Checklist
 - [-] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [-] I have checked if this issue already exists (both open and closed issues)
 - [-] I am using the most recent version of pogom from the master branch
 - [N/A] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [N/A] I'm posting the complete log
 - [-] I'm using a descriptive title for this issue

## My Issue

It appears my IP has been banned from accessing tracking features on Pokemon Go. I've had pogom running for about 48 hours now, and it's worked seamlessly apart from a couple times when the front end web server has suddenly become inaccessible, but that's easily fixed with a restart.

I noticed that although the scan was progressing, no pokemon were appearing on my map. So I logged into my personal account whilst connected to WiFi (same network I'm hosting pogom on and noticed that the app told me "No Sightings". I then reloaded the app on my 4G data plan and there were slightings.

Is this IP ban on tracking features a soft ban or permanent, if not permanent, how long does the ban last? And is there any way around this so I can get back online again?

Thanks,
Michael

**Comment by Mickey32111** [comment]
NOTE: I have not been getting the rate limited error

**Comment by J-D-A** [comment]
Same thing for me, seems to be an IP ban.

**Comment by Mickey32111** [comment]
Turning it off for an hour and reloading it seems to work, but it's too soon to tell how long this will work for until my IP gets flagged again.

**Comment by RobinKuiper** [comment]
I have the exact same thing, stopped it now, and will try again in the morning.

**Comment by snicker** [comment]
Probably related to #205 

I got a softban too, I have stopped using pogom until #205 is resolved

**Comment by NWest707** [comment]
So i wasnt getting any error but still getting no pokemon.  However when i log onto my phone on the same wifi i get sighting.  It cant be an IP ban for me then correct?  I have no idea what the issue is.

**Comment by Mickey32111** [comment]
I can replicate #205 too.
![screen shot 2016-08-11 at 02 10 53](https://cloud.githubusercontent.com/assets/5605121/17576303/ec69b6d4-5f68-11e6-962b-a91af6808e05.png)

**Comment by Krooked733** [comment]
Same problem here - depending of the number of workers I got ip-banned. 350+ Workers = Banned after a few minutes. With less workers (around 100) it works for hours.

**Comment by weiguken** [comment]
@Krooked733 what scan radius/how many locations with 100 workers was it ok?

**Comment by Krooked733** [comment]
@weiguken 3 Locations with 2x:  2000 km and 1x: 3500 km - full scan around 10 minutes.

**Comment by mrfantomex** [comment]
Are you changing the number of works in code or is that a flag I don't know about?

**Comment by NWest707** [comment]
number of accts = workers

**Comment by favll** [comment]
@snicker @Mickey32111 #205 has been resolved

**Comment by Mickey32111** [comment]
@nborrmann Solving #205 subsquetually solved this issue. Probably safe to close.
