### ISSUE TITLE
Certain accounts wont log in correctly

### ISSUE THREAD

**Issue by throwpigeyaway** [favll/pogom#215]
## Checklist
 - [x] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [x] I have checked if this issue already exists (both open and closed issues)
 - [x] I am using the most recent version of pogom from the master branch
 - [ ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ ] I'm posting the complete log
 - [x] I'm using a descriptive title for this issue

## My Issue

I created some PTC accounts, accepted TOS on all also verified email, half of them wont log in, saying I have wrong password, thus creating a 15 min lock. After the lock, I log into PTC itself, and the accounts logged in successfully there. Not sure if it is client side or PTC side.
...

**Comment by Mickey32111** [comment]
Note: I have not been getting the rate-limited error.

**Comment by nborrmann** [comment]
Check the config.json file in the pogom folder to see if the password and username were parsed correctly.

**Comment by throwpigeyaway** [comment]
config.json file looked fine. exactly the same input as UN:PW.

**Comment by throwpigeyaway** [comment]
no solution , still a problem but ill close this.
