### ISSUE TITLE
Pokemon not showing up on mobile

### ISSUE THREAD

**Issue by TheUrbanNinja** [favll/pogom#216]
## Checklist
 - [x] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [x] I have checked if this issue already exists (both open and closed issues)
 - [x] I am using the most recent version of pogom from the master branch
 - [ ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ ] I'm posting the complete log
 - [x] I'm using a descriptive title for this issue

## My Issue
Pokemon show up fine on the computer but on phone nothing shows up.
...

**Comment by nborrmann** [comment]
Don't tell us what phone and browser you're using, that won't help us.

**Comment by TheUrbanNinja** [comment]
My bad, I'm using a iPhone 6 with Google Chrome.

**Comment by Crisicus** [comment]
Did a new clone from yesterday, same issue. iPhone 6S Safari. If I leave it open, new pokemon show up 1 by 1. PC works fine

**Comment by bigcross** [comment]
My problem is pokemon shows outside the circle. Not in accurate position.
iPhone 6s plus, safari.

**Comment by Faskill** [comment]
Got the same issue :

Iphone 5 with safari + ngrok tunnel

**Comment by dikkedeur** [comment]
got the same, at first i thought that the scanner was stuck, but logged in on terminal to see it was happy scanning all the time.
went on my macbook, safari and chrome, both shows the pokemons along with notification, going back to my mobile.. nothing, installed chrome on iphone6 same result.
so on iphone 6 chrome and safari dont work after some time.

**Comment by Waterkryx** [comment]
I got the same issue.. On desctop i can see all pokemons but on iphone 6s and iphone 5s i see only pokemon what expired now.

**Comment by robertftw** [comment]
Me too since the latest commits...

**Comment by dikkedeur** [comment]
has it something to do with the new feature that notifies ??
it did work for me yesterday

**Comment by thibthib** [comment]
On my iPhone 6S, I have some JS errors thrown by the new notification feature : 

<img width="750" alt="capture d ecran 2016-08-11 12 00 48" src="https://cloud.githubusercontent.com/assets/1030644/17588360/96dbf48c-5fce-11e6-9565-9fd9fe4a5191.png">

**Comment by robertftw** [comment]
@thibthib Good find, wrapping the notify method in try/catch inside notify.js and and adding `if (Notification === null || !Notification) {` to line 111 solved the issue for me.

**Comment by nborrmann** [comment]
@robertftw Nice, can you send a pull request?

**Comment by Crisicus** [comment]
Doesn't Chrome in iOS support notifications natively?

**Comment by robertftw** [comment]
@nborrmann it's not a pretty solution, I rather have the developer solve it in a better way. Besides i don't know how to do a pull request in GitHub 😏

**Comment by nborrmann** [comment]
Thanks for the error log.

Possibly fixed in 2855bfc. Please comment if the issue persists.
