### ISSUE TITLE
Current Scan: 0.00% w/o update

### ISSUE THREAD

**Issue by throwpigeyaway** [favll/pogom#217]
![Uploading Screen Shot 2016-08-10 at 1.22.42 PM.png…]()
## Checklist
 - [x] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [x] I have checked if this issue already exists (both open and closed issues)
 - [x] I am using the most recent version of pogom from the master branch
 - [ ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ ] I'm posting the complete log
 - [x] I'm using a descriptive title for this issue

## My Issue

The current scan always says its at "0.00%".
...

**Comment by nborrmann** [comment]
Duplicate (too lazy to find the ID)
