### ISSUE TITLE
Notifications not appearing 

### ISSUE THREAD

**Issue by jmdelatorre** [favll/pogom#218]
## Checklist
 - [ x] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [ x] I have checked if this issue already exists (both open and closed issues)
 - [ x] I am using the most recent version of pogom from the master branch
 - [ x] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ x] I'm posting the complete log
 - [ x] I'm using a descriptive title for this issue

## My Issue
Hi,

Notifications are not appearing when a pokemon spwan. I enabled it on any pokemon and notifications are never appearing. I approved the notifications on Chrome. Do I have to enable it anywhere else?

Also, how probable is it to get banned when connecting through the same wifi using 3 accounts for scanning?

thanks

**Comment by wilsonwc** [comment]
Can you open up the developer tools in chrome and see if there are any errors in the console (Menu in the top right->More Tools->Developer Tools).  Paste a screenshot or the text here

**Comment by jmdelatorre** [comment]
Out of the blue it started working (got hundreds of notifications) thanks anyways

**Comment by brendenpetersen** [comment]
I'm having this issue. I never received a request for notifications (which is my default Chrome option). I also manually added 127.0.0.1:5000 to the exceptions list to allow notifications.
