### ISSUE TITLE
Error in worker thread. Returning empty response......

### ISSUE THREAD

**Issue by Banjorune** [favll/pogom#221]
## Checklist
 - [x] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [x] I have checked if this issue already exists (both open and closed issues)
 - [x] I am using the most recent version of pogom from the master branch
 - [x] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [x] I'm posting the complete log
 - [x] I'm using a descriptive title for this issue

## My Issue

I keep getting this error:
016-08-10 23:26:11,422 [   auth_ptc] [  ERROR] PTC Login failed.
2016-08-10 23:26:11,422 [     pgoapi] [  ERROR] Error in worker thread. Returning empty response. Error: local variable 'r' referenced before assignment
2016-08-10 23:26:11,422 [       scan] [   INFO] Map Download failed. Trying again.
...

I have had this error for over 2 days now, and it works for my friend all the time. I try to run it from MAC, and he uses Windows.

Hope someone has any answers:)

**Comment by thappy** [comment]
how many workers are you using and are they ALL getting this?

**Comment by Banjorune** [comment]
Tried everything from 1 to 10 workers, and yes all is getting this error.

**Comment by pedrosodre** [comment]
Banjorune, where you changed workers number?

**Comment by Banjorune** [comment]
pedrosodre, it depends on how many ptc/google accs you add, if im not wrong :=)

**Comment by Crisicus** [comment]
@Banjorune Are you sure your accounts are verified and accepted ToS?
My scans used to get the same error untill I put the time into creating, accepting ToS and verifiying email for all of my 200 accounts.

https://github.com/FrostTheFox/ptc-acc-gen
https://github.com/TachyonRSA/PoGoTos
https://gist.github.com/sebastienvercammen/e7e0e9e57db246d7f941b789d8508186

**Comment by Banjorune** [comment]
Crisicus, I only accepted ToS on the first account. It doesent work on that either, but i will try to verify all the other accounts and see if it helps. (Don't think it will make any difference tho, my friend tried to use one of my PTC acc's on he's pogom map and it worked for him)...

**Comment by Banjorune** [comment]
I got a new error now when i tried to dobble click on the runserver.py file, (i usualy start it from the terminal).
IDEL´s Subprocess didn´t make connection. Either IDLE can´t start a subprocess or personal Firewall software is blocking the connection.

I looked at the firewall on the my MAC computer and is turned off....
