### ISSUE TITLE
Add CentOS signature lib

### ISSUE THREAD

**Issue by nakami** [favll/pogom#223]
## Checklist
 - [x] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [x] I have checked if this issue already exists (both open and closed issues)
 - [x] I am using the most recent version of pogom from the master branch
 - [x] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [x] I'm posting the complete log
 - [x] I'm using a descriptive title for this issue

## My Issue
the webserver won't start listening after i run the script. there are no errors in the log that i may resolve.

```
[foo@bar]~/Downloads/pogom-master% python2.7 runserver.py -P 63436
2016-08-10 23:26:26,759 [     pgoapi] [   INFO] pgoapi v1.1.7 - Copyright (c) 2016 tjado <https://github.com/tejado>
```
(also adding -d debug or -d info flag, doesn't give me any information either)

the server is not reachable on that port:
```
[foo@bar Downloads]$ netstat -tulpen | grep 63436
[foo@bar Downloads]$
```

OS, OS version, python version, pip version:
Running CentOS 6.8 with no root priviledges.
```
[foo@bar Downloads]$ cat /etc/redhat-release
CentOS release 6.8 (Final)

[foo@bar Downloads]$ python2.7 --version
Python 2.7.10

[foo@bar Downloads]$ pip2.7 --version
pip 7.1.2 from /package/host/localhost/python-2.7.10/lib/python2.7/site-packages (python 2.7)

```

also stuff that i had to deal with during installation:
- adding the --user argument to when installing requirements.txt with pip to install to userspace (because of being a non-root user)
- installing GLIBC 2.14 parallel (because centOS 6.X apparently doesn't support >2.12) according to the second comment on [this guide](https://unix.stackexchange.com/questions/176489/how-to-update-glibc-to-2-14-in-centos-6-5)

**Comment by Sociopaat** [comment]
run it with -H 0.0.0.0
works for me =)

**Comment by nakami** [comment]
your comment isn't really helpful...
how is providing an alternate IP-adress supposed to resolve my problem?

**Comment by SysQo** [comment]
Please do what @Sociopaat has recommended. If you read the setup instrutions you will notice that without providing an IP to bind to, the server is only accessible from 12.0.0.1

**Comment by nakami** [comment]
i tried the -H argument, it doesn't help. did you mean 127.0.0.1 instead of 12.0.0.1? im perfectly fine with my local IP being the one being listened to.
running a script with sudo is no option for me (sadly) and shouldn't be a reasonable fix on this honestly.

**Comment by SysQo** [comment]
After starting the script try to curl 127.0.0.1:port and see what happens

**Comment by Crisicus** [comment]
Your startup command should look like:
`python2.7 runserver.py -H "0.0.0.0"-P 63436`
sudo is not required

**Comment by nakami** [comment]
run the script with
`python2.7 runserver.py -H "0.0.0.0" -P 63436
`

another shell for curl:
```
[foo@bar ~]$ curl 0.0.0.0:63436
curl: (7) couldn't connect to host
[foo@bar ~]$ curl 127.0.0.1:63436
curl: (7) couldn't connect to host
```
maybe i missed something. but why don't i get any info on what i messed up?

**Comment by dingensundso** [comment]
I had the exact same problem. (Similar system, also running on uberspace :) ).
I dug a little into it and found out where it freezes. It's when it loads the encrypt lib ( https://github.com/favll/pogom/blob/master/pogom/pgoapi/rpc_api.py#L85 ).
Since PokemonGo-Map works, I looked what they do different. They have an extra library file for centos, so you don't need the newer glibc.
So to get pogom running on CentOS you need to grap https://github.com/PokemonGoMap/PokemonGo-Map/blob/develop/pogom/libencrypt/libencrypt-centos-x86-64.so?raw=true , put in into the lib dir and edit utils.py so it loads the right lib:

```
diff --git a/pogom/utils.py b/pogom/utils.py
index 7afafaa..12bba78 100644
--- a/pogom/utils.py
+++ b/pogom/utils.py
@@ -63,7 +63,9 @@ def get_encryption_lib_path():
         lib_path = os.path.join(lib_folder_path, "libencrypt-linux-arm-32.so")
 
     elif sys.platform.startswith('linux'):
-        if platform.architecture()[0] == '64bit':
+        if platform.dist()[0] == "centos":
+            lib_path = os.path.join(lib_folder_path, "libencrypt-centos-x86-64.so")
+        elif platform.architecture()[0] == '64bit':
             lib_path = os.path.join(lib_folder_path, "libencrypt-linux-x86-64.so")
         else:
```
Maybe someone could put this in a PR.

**Comment by joeubi** [comment]
You need to change -H to your local IP of the computer you are hosting it from.
 ex. `python2.7 runserver.py -H "192.168.2.105" -P 63436`
