### ISSUE TITLE
The scan is completed ad 101.44%

### ISSUE THREAD

**Issue by eugenio412** [favll/pogom#225]
## Checklist
 - [x ] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [ x] I have checked if this issue already exists (both open and closed issues)
 - [ x] I am using the most recent version of pogom from the master branch
 - [ x] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ x] I'm posting the complete log
 - [ x] I'm using a descriptive title for this issue

## My Issue

The scan is completed at 101.44% [![issue.png](https://s9.postimg.org/9ogagxh0f/issue.png)](https://postimg.org/image/5s2ykxw0r/)

**Comment by szeco** [comment]
this happens when you add/remove markers on the map the next full scan should revert back to 100%
