### ISSUE TITLE
Can't set a location (Error: Radius not valid)

### ISSUE THREAD

**Issue by Firehearted** [favll/pogom#229]
## Checklist
 - [x] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [x] I have checked if this issue already exists (both open and closed issues)
 - [x] I am using the most recent version of pogom from the master branch
 - [ ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ ] I'm posting the complete log
 - [x] I'm using a descriptive title for this issue

## My Issue

Somehow I'm not able to set a location marker on the map. It doesn't matter what numbers I put in, after clicking "add new location" I always get the error "Radius not valid. Please note that the radius' unit is in meters and must be a whole number. It also should be >100m."
Tried "10", "10m", "10 m" etc....what am I doing wrong/what am I missing? 
![bildschirmfoto 2016-08-11 um 13 56 26](https://cloud.githubusercontent.com/assets/20969648/17588015/3cfff622-5fcc-11e6-9d29-3a47fb300a4e.png)

I'm on OSX 10.10.5. 

Thanks for everything and keep up the great work everyone!

**Comment by nborrmann** [comment]
Enter a plain number that is bigger than 100.

**Comment by Firehearted** [comment]
Alright, thank you very much!
