### ISSUE TITLE
[Enhancement] Option to switch off the red pin from the map?

### ISSUE THREAD

**Issue by mlc130104** [favll/pogom#230]
In the mobile view, the pins are too big that even covered icons of scanned pokemons. So I guess it will be a great idea to add an option to hide those pins.

**Comment by nborrmann** [comment]
Pins are hidden when you hide the cover.

**Comment by mlc130104** [comment]
Sorry if I misunderstood you, but I have already hide the cover and both desktop and mobile view dont hide the pins

![screenshot aug 11 2016 9-34-12 pm](https://cloud.githubusercontent.com/assets/7189975/17590326/00c35e66-600c-11e6-9161-440bfb27aed1.png)
<img width="1423" alt="screen shot 2016-08-11 at 9 33 43 pm" src="https://cloud.githubusercontent.com/assets/7189975/17590342/066d8f94-600c-11e6-899d-365d75936cd9.png">

**Comment by nborrmann** [comment]
What version are you on?

**Comment by mlc130104** [comment]
I git-pulled a few hours ago so I assume that I am on a new version.

I mistook the "cover" as the option pane at the first time. The coverage option was off when screenshot. Turning it on and off again indeed removed the pins. But I witnessed this problem since last night (24hrs ago here). So I think this glitch is reproducible?
