### ISSUE TITLE
Implementing TBTerra's Spawn Tracker

### ISSUE THREAD

**Issue by stu177** [favll/pogom#231]
This could be a decent improvement to reduce connections and reduce amount of throttling:

https://www.reddit.com/r/pokemongodev/comments/4wxteh/i_implemented_tbterras_spawntracker_into/

**Comment by nborrmann** [comment]
dupe

**Comment by stu177** [comment]
I couldn't see another issue post about implementing this.

**Comment by lisandro52** [comment]
@stu177 #199 The title isn't very clear, but the issue is about exactly this.
