### ISSUE TITLE
Only can see settings on mobile browser

### ISSUE THREAD

**Issue by RollTideDG** [favll/pogom#233]
## Checklist
 - [ ] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [ ] I have checked if this issue already exists (both open and closed issues)
 - [ ] I am using the most recent version of pogom from the master branch
 - [ ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ ] I'm posting the complete log
 - [ ] I'm using a descriptive title for this issue

## My Issue
I am on iPhone 6+ and when I load the map in safari or chrome I can only see the settings. The close button on the settings doesn't work. Desktop works fine. 

I noticed some people are getting maps to load on iPhone and was wondering how they closed the settings pane to see the map
...

**Comment by nborrmann** [comment]
Possibly fixed in 2855bfcc1f18a3547e12696f09745647432b9f6e

**Comment by RollTideDG** [comment]
No didn't help.
When you click on the X to close the settings nothing happens on Safari or Chrome mobile browsers. Desktop works just fine.

**Comment by nborrmann** [comment]
Any way you could post the js console logs from your mobile? Dunno how that works on iphone  though.

**Comment by RollTideDG** [comment]
I don't think iPhone has JS console logs or if it does I don't know how to access them. I just pulled the latest build from master and it did not help.

**Comment by RollTideDG** [comment]
I was finally able to see a debug log by using remote debugging and this is the only error on the page

http://xxx.xxx.xxx.xxx:5001/static/notify.js:109
link
ReferenceError: Can't find variable: Notification

**Comment by RollTideDG** [comment]
Ok so I was able to remove the code from notify.js that was throwing errors and now I get no errors thrown.

Settings pane will still not slide back. Whatever .css functions are being called to slide or hide that pane are not supported in Mobile Safari or Chrome it appears.

**Comment by nborrmann** [comment]
i have pushed a fix for the js error. But can't help you with the css thing right now.

**Comment by nborrmann** [comment]
Maybe add the webkit prefix to all the css animstations statements like

```
 -webkit-transform: ..
 -webkit-transition: ..
```

**Comment by RollTideDG** [comment]
I get this error everytime I hit the close button in chrome:

http://xxx.xxx.xxx.xxx:5001/:3
link
ReferenceError: Can't find variable: fieldset

**Comment by RollTideDG** [comment]
@nborrmann Hey man that fixed it. 
All the transform and transitions need the -webkit- prefix.

**Comment by nborrmann** [comment]
Can you send a pull request?

**Comment by RollTideDG** [comment]
I've never done one before
