### ISSUE TITLE
[Request] -ns no server

### ISSUE THREAD

**Issue by vinsilsim** [favll/pogom#235]
## Checklist
 - [x ] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [ x] I have checked if this issue already exists (both open and closed issues)
 - [ x] I am using the most recent version of pogom from the master branch
 - [ x] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ x] I'm posting the complete log
 - [ x] I'm using a descriptive title for this issue

## My Issue

it is possible to deploy no server?

...

**Comment by nborrmann** [comment]
No
