### ISSUE TITLE
Stuck in loging loop after accounts login expires

### ISSUE THREAD

**Issue by TheGreyPigeon** [favll/pogom#239]
Hello,
Many thanks for this incredible map. 
I'm running into the following problem.
After the ptc logins expires the program logs all accounts in again successfully , yet for some accounts the "login is about expire " message remains and tries to log in again and again. meanwhile the scan does not continue.  
It is not always the same accounts which get stuck.
Ill include a screenshot of the terminal, at the top you can see that the login is successful.
Thanks again !
![screenshot from 2016-08-11 23-31-08](https://cloud.githubusercontent.com/assets/20978635/17605854/cd5ef0ce-601c-11e6-9bd3-ebb8c0849e82.png)

**Comment by nborrmann** [comment]
Duplicate and also already fixed.
