### ISSUE TITLE
Unable to see anything on the map

### ISSUE THREAD

**Issue by samsbase** [favll/pogom#24]
Here is my javascript console as promised

http://puu.sh/qfHQi/67b80d027d.png

**Comment by nborrmann** [comment]
Ok, I see. The problem is with the ES6 template strings in line 100-137 of maps.js.

I'll fix it tomorrow (if nobody sent a pr until then).

**Comment by samsbase** [comment]
brilliant thanks

**Comment by nborrmann** [comment]
Should be fixed in ea72e2c24e1b5c53cacf37a7aeb68087eb9b0583. Please comment if it still doesn't work. Closing this for now.
