### ISSUE TITLE
Unable to remove notifications for a Pokemon. 

### ISSUE THREAD

**Issue by poloka** [favll/pogom#242]
Tested receiving notifications using a pidgey but now can't remove the notification.  So every refresh I get pidgey notifications.

**Comment by Greg117** [comment]
This does seem like a bug.  Meanwhile, you can go to stats and uncheck the notification.

**Comment by Mickey32111** [comment]
I can +1 this, unchecking notification in stats made no difference for me, had to clearly my cache and cookies to get it to stop.

**Comment by nborrmann** [comment]
That's a limitation of the browser notifications. If you get several dozen notifications at once and they will all appear as you close the previous notifications. There's afaik no way to mass-dismiss notifications.
