### ISSUE TITLE
Possible Map Error?

### ISSUE THREAD

**Issue by TheUrbanNinja** [favll/pogom#244]
## Checklist
 - [x] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [x] I have checked if this issue already exists (both open and closed issues)
 - [x] I am using the most recent version of pogom from the master branch
 - [ ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ ] I'm posting the complete log
 - [ ] I'm using a descriptive title for this issue

## My Issue
Today I noticed while running the map there was a Kabutops that would expire and and re-spawn in the same exact location which happened about 6-7 times with a remaining time anywhere from 30 seconds up to 2 minutes. I heard that appereanly some Pokemon have 30 minute spawn timers but the first 15 minutes is returned negative when using  the function time_till_hidden_ms and negatives are not supported in java. Not sure if that is the issue but thought i should just mention it.
...

**Comment by nborrmann** [comment]
#213
