### ISSUE TITLE
[Feature Request] Save Pokemon Exclusion and Notification Settings

### ISSUE THREAD

**Issue by hanscts** [favll/pogom#245]
## Checklist
 - [x] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [x] I have checked if this issue already exists (both open and closed issues)
 - [x] I am using the most recent version of pogom from the master branch
 - [ ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ ] I'm posting the complete log
 - [x] I'm using a descriptive title for this issue

## My Issue

...
Hide common Pokemon and notification settings already persist on the same browser. But is there a way to save these settings so it persist across different devices/browsers as well? Maybe save it in the config file, or even better, profile based settings?

Also, does anyone know where the settings are currently saved? In cookies? Any ways to transfer them between browsers or devices?

Thanks.

**Comment by nborrmann** [comment]
The usage model is "one server, multiple users" so it doesn't make sense to save this server side.

The settings are saved in the browser  localStorage.

Also dupe.
