### ISSUE TITLE
[Suggestion] Implementing spawn.json targeted search

### ISSUE THREAD

**Issue by szeco** [favll/pogom#247]
## Checklist
 - [x] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [x] I have checked if this issue already exists (both open and closed issues)
 - [x] I am using the most recent version of pogom from the master branch
 - [ ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ ] I'm posting the complete log
 - [x] I'm using a descriptive title for this issue

## My Issue
Hi @favll / @nborrmann , how feasible is it to implement the targeted search via a spawn.json that's all the rage on dev reddit these days?  Got this working on the PokemonGo-Map and saw a number of people asking if this version will support it.

Link: https://www.reddit.com/r/pokemongodev/comments/4wxteh/i_implemented_tbterras_spawntracker_into/?sort=new&limit=500
...

**Comment by djv2** [comment]
+1 would be awesome

**Comment by nborrmann** [comment]
Dupe
