### ISSUE TITLE
Sometimes duplicates of the same Pokemon occur multiple times in the database

### ISSUE THREAD

**Issue by asdfMaciej** [favll/pogom#248]
## Checklist
 - [+] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [+] I have checked if this issue already exists (both open and closed issues)
 - [+] I am using the most recent version of pogom from the master branch
 - [+] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [-] I'm posting the complete log
 - [+] I'm using a descriptive title for this issue

## My Issue
It occurs to me a bit often, that multiple records of the same Pokemon appear in the database. They appear to have their disappear time changed, but the rest remains the same.
Example log:
MjAxMDc1ODYyMDQwODEzMzk2NQ==,47041db71bb,143,52.713502494651,16.3650784146501,2016-08-11 20:20:29
MjAxMDc1ODYyMDQwODEzMzk2NQ==,47041db71bb,143,52.713502494651,16.3650784146501,2016-08-11 20:23:31
MjAxMDc1ODYyMDQwODEzMzk2NQ==,47041db71bb,143,52.713502494651,16.3650784146501,2016-08-11 20:26:30
MjAxMDc1ODYyMDQwODEzMzk2NQ==,47041db71bb,143,52.713502494651,16.3650784146501,2016-08-11 20:29:27
MjAxMDc1ODYyMDQwODEzMzk2NQ==,47041db71bb,143,52.713502494651,16.3650784146501,2016-08-11 20:32:27
MjAxMDc1ODYyMDQwODEzMzk2NQ==,47041db71bb,143,52.713502494651,16.3650784146501,2016-08-11 20:35:17.708000
I don't know how to replicate this bug.
I'm using Python 2.7.6, pip 8.1.2 on Windows 7 Ultimate.
...

**Comment by Shadowfish26** [comment]
Confirming that I am also seeing this problem and it can happen with multiple pokemon at the same time. Doesn't happen for all Pokemon however.

**Comment by nborrmann** [comment]
Fixed in 08164c0857d5d5af5db7bffb92e5442f47ced84d. 

You possibly need to delete the database though.
