### ISSUE TITLE
Notifications via email or sms

### ISSUE THREAD

**Issue by dawie180** [favll/pogom#249]
Hi,

I was using pokemongomap previously before it was shut down and i was able to edit the script (as a noob) and was able to get it to send me a sms  (bulksms) when a predefined pokemon  pokemon appeared and the sms contained the name of the pokemon, its dissappear time and a clickable google maps link directing you to it.  Im struggling to impliment it in your script, any ideas?

**Comment by dawie180** [comment]
BTW, you guys are legends!

**Comment by 001nathan100** [comment]
I would love the ability to get a phone notification somehow!

**Comment by dawie180** [comment]
It worked so well, im very inexperienced in python but i managed to get it working flawlessly.

This is how the sms comes, i just copied it...

Squirtle -  http://maps.google.com/?q=-33.860078,18.535788   Disappears at: 2016-07-26 22:33:01.358000

**Comment by 001nathan100** [comment]
An email would work for me too tbh

**Comment by dawie180** [comment]
Ya i knw, i worked with bulksms before so it was easier to implement. Email is free where im paying for sms credits now, but its cheap.

**Comment by eugenio412** [comment]
I used to code for telegram bots, I could do something with that! but I can't fully understand this library, baby steps

**Comment by eugenio412** [comment]
made a telegram bot in #279

**Comment by dawie180** [comment]
@eugenio, u are a legend... only 1 small problem, how does one scan for many pokemon and not just 1?

**Comment by eugenio412** [comment]
Still working on it, I need an array for rare, ultra rare Pokemon etc etc

**Comment by eugenio412** [comment]
Done, now it supports the notification based on rarity, but I moved to https://GitHub.com/eugenio412/pogoBOT

**Comment by Aabhapure** [comment]
hii
Get best <a href=http://technorelease.com/top-5-bulk-sms-service-provider-in-india-with-sms-api/>Bulk SMS service provider in India</a> to relate with your customer.
