### ISSUE TITLE
[REQUEST & ISSUES]

### ISSUE THREAD

**Issue by Jones1337** [favll/pogom#250]
## Checklist
 - [X] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [X] I have checked if this issue already exists (both open and closed issues)
 - [X] I am using the most recent version of pogom from the master branch
 - [ ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ ] I'm posting the complete log
 - [ ] I'm using a descriptive title for this issue

## My Issues & Requests
- Multiple notifications of same pokemon with wrong timer
- Notifications on mobile doesn't work yet (iOS 9.3.4, tested browser: safari, chrome, opera)
- need a list of scanned locations to make navigation easy
- need data of every single scanned pokemon and show on map like on "PokemonGo-Map" (date, time, number of spawned pokemon of same species) [Improvement of Pokestats]

I really would like to implement this on my own for us, but unfortunately i'm not familiar with Python :-(
I don't want you to implement the improvements above immediately, but i want to know if there is any chance the devs are working on something like that.

Thank you for reading and not flaming ;-) !!!

**Comment by nborrmann** [comment]
> I'm using a descriptive title for this issue
> I have checked if this issue already exists (both open and closed issues)
