### ISSUE TITLE
[Request]  Set default location opening.

### ISSUE THREAD

**Issue by omlet05** [favll/pogom#256]
Hi,

Is there any way to implement to open the map at location we want?
I was looking into the code but didn't find anything...

Regards,

**Comment by jxjftw** [comment]
pogom/static/map.js

```
function initMap() {
    var initLat = 40.782850;  // NYC Central Park
    var initLng = -73.965288;
```


Change the lat/lon to what you want. Although, if you have scans setup, whenever you open the page, the map will center to where your scans are.

**Comment by omlet05** [comment]
Thanks a lot !
