### ISSUE TITLE
Webserver not working from other devices

### ISSUE THREAD

**Issue by diputz42** [favll/pogom#257]
I've forwarded ports 5000-5050 on my router to my server, and the web server was working fine with other mapping tools. But it seems to not work with pogom, even with -H 0.0.0.0 and -P 5000 argument in command line. I'm running my server on Windows 7 x64.

The webserver works fine from the same machine hosting the server, when I visit 127.0.0.1:5000.

**Comment by joeubi** [comment]
I had to change -H to the local IP of the computer I was hosting it from. My local IP was 192.168.2.106 so I set mine to -H 192.168.2.106 -P 5000.

**Comment by diputz42** [comment]
Thanks for that! Seems to work for me too.
