### ISSUE TITLE
Accounts are not active anymore, 

### ISSUE THREAD

**Issue by dikkedeur** [favll/pogom#261]
## Checklist
 - [x ] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [x ] I have checked if this issue already exists (both open and closed issues)
 - [x ] I am using the most recent version of pogom from the master branch
 - x[ ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [x ] I'm posting the complete log
 - [x ] I'm using a descriptive title for this issue

## My Issue
suddenly accounts are not active anymore
...
suddenly my 50 accounts are not active anymore
my server was scanning normal for more then 24 hours, and suddenly i saw that scans of my area took longer then normal.
now when i got home i saw this in the log

2016-08-12 22:13:14,779 [   auth_ptc] [  ERROR] Could not retrieve token: Account is not yet active, please redirect.
2016-08-12 22:13:14,779 [   auth_ptc] [  ERROR] Could not retrieve token: Account is not yet active, please redirect.
2016-08-12 22:13:14,790 [   auth_ptc] [  ERROR] Could not retrieve token: Account is not yet active, please redirect.
2016-08-12 22:13:14,820 [   auth_ptc] [  ERROR] Could not retrieve token: Account is not yet active, please redirect.
2016-08-12 22:13:14,825 [   auth_ptc] [  ERROR] Could not retrieve token: Account is not yet active, please redirect.

**Comment by joeubi** [comment]
What happens when you try and log in with the app?

**Comment by dikkedeur** [comment]
did a test, there where accounts made by hand, those still work.
but the accounts made with an account maker not anymore.
seems that nia changed it.
on the other hand i heard that this was also an automatic process on this map to activate accounts... not sure.

**Comment by dikkedeur** [comment]
okay when i try to login on the account on the app i get that the login and password are incorrect.
it seems that Nia is blocking or banned massively created accounts made by the account creation tool.
Still not sure.. i can be wrong.

**Comment by dikkedeur** [comment]
i must say that it is different, 
the account is not banned just not active, you must activate now in the e-mail, which is something you dont have if you make accounts with those massive account tool.
so i think there must be found another way to activate accounts.

**Comment by Lionir** [comment]
@dikkedeur Account creation tools never verified the accounts since they use completely random emails so you'd need to make accounts every day using the tool but currently, no account creation tool work since PTC now has a captcha making it impossible for those tool to create the PTC account.

**Comment by dikkedeur** [comment]
so we are screwed, or just scan with few very few accounts.. that would make it take a long time and not to speak... impossible to scan some areas.
since if it takes longer then 5 minutes the spawn might be already gone.

**Comment by djv2** [comment]
i don't know why you are posting account issues on github, a development repository. that is completely irrelevant
