### ISSUE TITLE
[new request] scan followed location

### ISSUE THREAD

**Issue by Jones1337** [favll/pogom#263]
## Checklist
 - [X] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [X] I have checked if this issue already exists (both open and closed issues)
 - [X] I am using the most recent version of pogom from the master branch
 - [ ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ ] I'm posting the complete log
 - [X] I'm using a descriptive title for this issue

## Improvement request
I definitly miss the option to scan the followed location.
What do you guys think about it?
...

**Comment by nborrmann** [comment]
#263
