### ISSUE TITLE
[Suggestion/Improvement] Stats of a specific location

### ISSUE THREAD

**Issue by veamorim** [favll/pogom#269]
## Checklist
 - [x] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [x] I have checked if this issue already exists (both open and closed issues)
 - [x] I am using the most recent version of pogom from the master branch
 - [ ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ ] I'm posting the complete log
 - [x] I'm using a descriptive title for this issue

## My Issue
The idea here is to show a button right next to "Delete Location" button which displays a list of the pokemon found in that location.
Why?
Let's say that my friend found an Aerodactyl in an area, then the next day he find it again nearby the same place he found the first one. It would be really good to set a tracking there and let it scan for a few hours (or a whole day) and check if that area is has a spawn of Aerodactyls.
...

**Comment by dikkedeur** [comment]
isnt there heatmaps for??
with the heatmaps you can see specific spawnpoints where for example aerodactyl spawns..
try it out and see if that fits your needs.

**Comment by iMagooo** [comment]
Heatmaps implements this functionality.

**Comment by nborrmann** [comment]
That's kinda what heatmaps do.
