### ISSUE TITLE
Ridiculous huge amount of time left for pokemons

### ISSUE THREAD

**Issue by LuissRicardo** [favll/pogom#271]
![bug](https://cloud.githubusercontent.com/assets/8435110/17641688/4228ede6-60f0-11e6-90c3-2bc915bc40cf.PNG)

In the previous picture you can see that 2 pokemons have a huge amount of time left to expire, while others have a normal amount of time left to expire. There's a few more like this in the area.

As the problem is not crashing, or malfunctioning I didn't know what type of log to include in the Issue.

**Comment by chezbgone** [comment]
See [#260](https://github.com/favll/pogom/issues/260).
