### ISSUE TITLE
Periodically need to restart map

### ISSUE THREAD

**Issue by CuRleGit** [favll/pogom#272]
Hello there.

Today I have had to keep restarting my server after about an hour of uptime. My map will suddenly stop returning results and the command window will give me a message telling me that two of my seventeen accounts token's  have expired. As soon as I stop and start the server, everything works fine.

Does anyone have a batch file to restart/close and reopen their server after a period of time?

**Comment by CuRleGit** [comment]
I may have crated a band aid fix for this, with the help of task scheduler. It's a few years since I did any sort of decent coding, so this is the best I could come up with.

Create a batch file with taskkill /im python.exe

Schedule a task to run that .bat and then run runserver.py (inside pogom folder).
Add -H X.X.X.X and -P XXXX in arguments for runserver,py, if necessary.

I've got this repeating every 30 minutes.
Let's see how it goes.

**Comment by tier4fusion** [comment]
This is pretty similar to the issue I used to have, where it just gets stuck logging in the accounts. My fix was just to restart my Raspberry Pi every hour and it seems to work fine.

**Comment by iMagooo** [comment]
Are you using the latest source? A login loop was recently patched.

**Comment by CuRleGit** [comment]
I believe so. The last time I updated was today or yesterday.
I have the back to map button on stats page, which I think was the last change.

**Comment by iMagooo** [comment]
Do a git pull and then provide logs of the issue.

**Comment by nborrmann** [comment]
We had a bug earlier, but it was fixed and the newest version has been running fine for hours on my server. Please provide logs.

**Comment by Mickey32111** [comment]
Pulling the latest source fixed this for me.
