### ISSUE TITLE
Icon size too small to see

### ISSUE THREAD

**Issue by dennislwy** [favll/pogom#273]
Even viewing on a iPhone 6, most of the time i find it difficult to see and make out what Pokemon is it (especially while you running towards to find it)  

Left hand side is current (a bit small), right hand side is [PokemonGo-Map](https://github.com/PokemonGoMap/PokemonGo-Map) (just nice)  
![img_4626](https://cloud.githubusercontent.com/assets/5407099/17642694/2e2d10d2-6182-11e6-9875-8fbda5af3ff0.jpg)

Can you make pokemon icons bigger or adjustable?

**Comment by Jones1337** [comment]
+1 need this!

**Comment by nborrmann** [comment]
I like it as it is, if you need this change, go to map.js and change the size in line 284.
