### ISSUE TITLE
579h spawn time bugg

### ISSUE THREAD

**Issue by Chrallas** [favll/pogom#274]
## Checklist
 - [ ] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [ ] I have checked if this issue already exists (both open and closed issues)
 - [ ] I am using the most recent version of pogom from the master branch
 - [ ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ ] I'm posting the complete log
 - [ ] I'm using a descriptive title for this issue

## My Issue

Everything works Great but when The scanner finds pokemons some Times they appears with 579h and 17 minutes and I checked they dont exists longer than 15 minutes. Any solutions? I have tried delete The database files so their server make a new one.

**Comment by mmaasbo** [comment]
Please see existing issue #260

**Comment by labaland** [comment]
@mmaasbo , so what to do with the "WildPokemon.proto" file ?! change this 
"message WildPokemon {
	fixed64 encounter_id = 1;
	int64 last_modified_timestamp_ms = 2;
	double latitude = 3;
	double longitude = 4;
	string spawn_point_id = 5;
	.POGOProtos.Data.PokemonData pokemon_data = 7;
	int32 time_till_hidden_ms = 11;"

to this? -

"message WildPokemon {
	fixed64 encounter_id = 1;
	int64 last_modified_timestamp_ms = 2;
	double latitude = 3;
	double longitude = 4;
	string spawn_point_id = 5;
	.POGOProtos.Data.PokemonData pokemon_data = 7;
	int64 time_till_hidden_ms = 11;"
???
yes im new to this :D

**Comment by mmaasbo** [comment]
That fix does not work unfortunately, you can try #266

**Comment by labaland** [comment]
@mmaasbo BIG Thank you! Works now :) !

**Comment by dennislwy** [comment]
after clean affected record in db, #266 solution work for me

**Comment by nborrmann** [comment]
fixed

**Comment by Bizadon** [comment]
@nborrmann can you help please and say how to clear database with 579h pokemons? Restart of server doesnt help.

**Comment by nborrmann** [comment]
Delete the database.

**Comment by Bizadon** [comment]
Thanks, i'll try it
