### ISSUE TITLE
Authentication for everyone?

### ISSUE THREAD

**Issue by Sociopaat** [favll/pogom#276]
when i log in on my computer it seems that everyone that's using the map is authenticated also
I have this map for my city and many others use it now and it keeps authenticated bc they keep it open? Authenticated for hours now 

Already deleted the server configuration links but everyone can put new points and delete them

**Comment by nborrmann** [comment]
If you didn't set a password, everyone is authenticated by default. Otherwise this shouldn't be happening. Keep in mind, that the UI-label in the sidebar only updates if you do a full page refresh, so the auth-info might be out-of-date, any calls that need auth will be rejected though.
