### ISSUE TITLE
Large disappear time pokemon still on map after recent fixes

### ISSUE THREAD

**Issue by Clavus** [favll/pogom#278]
## Checklist
 - [x] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [x] I have checked if this issue already exists (both open and closed issues)
 - [x] I am using the most recent version of pogom from the master branch
 - [ ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ ] I'm posting the complete log
 - [x] I'm using a descriptive title for this issue

## My Issue

The large disappear time was fixed in recent commits, but even after pasting in the latest master branch, I still have a several clusters of 550+ hour disappear time Pokes on my map. Is there a way to clear these manually?

**Comment by nborrmann** [comment]
Delete the db. Or, if you know sql, manually delete all pokemon with a disappear_time in the large future.

**Comment by TheHippo** [comment]
As a hint:

* In terminal navigate to installation folder
* stop server
* `sqlite pogom.db` (in some case it's `sqlite3`)
* `delete from pokemon where disappear_time > '2016-08-14 00:00:00';` (replace time with something that more than 1h away from the time of your server)
* start server
