### ISSUE TITLE
Pokemon Repeatedly Spawning With About A Minute Left

### ISSUE THREAD

**Issue by halorrr** [favll/pogom#280]
## Checklist
 - [x] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [x] I have checked if this issue already exists (both open and closed issues)
 - [x] I am using the most recent version of pogom from the master branch
 - [ ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ ] I'm posting the complete log
 - [x] I'm using a descriptive title for this issue

## My Issue

Some Pokemon are spawning on my map with a minute left till they disappear (usually anywhere between 45 to 55 seconds to be exact) and when the minute is finished I just get another notification say that they have another minute till they disappear. This will go on for 15 - 30 minutes till they actually despawn.

I've had this happen with Eevee, Squirtle, Vulpix, Machop, and Warturtle so far and it gets really annoying.

**Comment by nborrmann** [comment]
Which commit are you on?

**Comment by halorrr** [comment]
Oh shoot, I updated about 4 hours ago, looks like there have been 5 commits since then, I'll try to see if that fixes it.
