### ISSUE TITLE
Colon in password

### ISSUE THREAD

**Issue by DanielBallaSZTE** [favll/pogom#281]
Hi, huge problem here:

All my PTC accounts have ":" (colon) in the password, and I can not configure the server because of it. Any solutions, or suggestions? Thanks in advance.

**Comment by dingensundso** [comment]
You could try editing the config.json

**Comment by mmaasbo** [comment]
I have not tested this my self, but I guess you edit _line 105_ in _pogom/app.py_. Here you define which symbol that splits username and password.

For example, from:
```
 if accounts_str:
            for a in accounts_str.splitlines():
                a = a.split(":")
                if (len(a) == 2) and (a[0].strip() not in usernames):
                    accounts_parsed.append({'username': a[0].strip(), 'password': a[1].strip()})
                    usernames.add(a[0].strip())
```

To:
```
if accounts_str:
            for a in accounts_str.splitlines():
                a = a.split(";")
                if (len(a) == 2) and (a[0].strip() not in usernames):
                    accounts_parsed.append({'username': a[0].strip(), 'password': a[1].strip()})
                    usernames.add(a[0].strip())
```

(now ';' will be the separator)

**Comment by DanielBallaSZTE** [comment]
Thanks mmaasbo, works like a charm, love you
