### ISSUE TITLE
Request: Add timing to Heatmaps

### ISSUE THREAD

**Issue by Coalado** [favll/pogom#282]
The Heatmap feature is great, but it would be even better, if you could click a Heatspot and see an time-aggregation of the previous spawns in the DB.

If there are no fixed time slots, and the spawns are kind of random, this would not make much sense, of course.

**Comment by nborrmann** [comment]
I have no idea what you're proposing. Please elaborate.

**Comment by Coalado** [comment]
Let's assume that certain pokemons spawn in regular time intervals (like every 90 Minutes), or at fixed time slots (Like daily at 12:30).

If  there is any scheme, it would be nice to  show it when clicking on a heat spot.

A very easy solution would be to show the last x pokemons that spawned at this point and when.
