### ISSUE TITLE
Status code 3 returned. Performing get_player request.

### ISSUE THREAD

**Issue by Epherex** [favll/pogom#284]
Checklist
 - [x] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [x] I have checked if this issue already exists (both open and closed issues)
 - [x] I am using the most recent version of pogom from the master branch
 - [x] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ ] I'm posting the complete log
 - [x] I'm using a descriptive title for this issue

## My Issue
The server starts normally, logs into all accounts, some of them (very few) starts scanning, but I keep getting the message "Status code 3 returned. Performing get_player request.", and eventually that's the only message I get from the server.

**Comment by nborrmann** [comment]
> I'm posting the complete log
