### ISSUE TITLE
How do I add a different notify sound?

### ISSUE THREAD

**Issue by Cromi38** [favll/pogom#286]
How do I add a different notify sound?  I have attempted to change the file of notify.mp3 but the new sound won't play even if I delete the database and start fresh.  Can anyone help with this? The notify sound doesn't stand out enough for me at times so it would be extremely useful.  Thank you

**Comment by nborrmann** [comment]
>change the file of notify.mp3

This. Maybe make a forced refresh in your browser, or delete the cache.
