### ISSUE TITLE
Best way to create PTC accounts?

### ISSUE THREAD

**Issue by hihellosm** [favll/pogom#287]
## Checklist
 - [x] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [ ] I have checked if this issue already exists (both open and closed issues)
 - [x] I am using the most recent version of pogom from the master branch
 - [ ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ ] I'm posting the complete log
 - [x] I'm using a descriptive title for this issue

## Best way to create PTC accounts?

The FAQ recommends having multiple PTC accounts for quicker scans. I noticed via other issues that some people have as much as 240 accounts!

Is there a suggested method for creating multiple PTC accounts other than manually doing so via the [website](https://www.pokemon.com/us/pokemon-trainer-club)?

**Comment by Mickey32111** [comment]
There used to be, but they added a captcha to the signup form. The guys behind pikapy are working on a workaround though.
