### ISSUE TITLE
Expired pokemon still show

### ISSUE THREAD

**Issue by janw-oostendorp** [favll/pogom#288]
## Checklist
 - [x] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [x] I have checked if this issue already exists (both open and closed issues)
 - [x] I am using the most recent version of pogom from the master branch
 - [ ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ ] I'm posting the complete log
 - [x] I'm using a descriptive title for this issue

## My Issue
Some expired Pokemon remain on the map.
I capture all output of the script but I can't find anything.

I'm just using a default setup. These pokemon have expired hours ago.
Does anybody have an idea?
What kind of information would be usefull?

![screenshot from 2016-08-14 05-44-10](https://cloud.githubusercontent.com/assets/1026882/17647050/280d8956-61e2-11e6-8941-e23a3749461b.png)

**Comment by Mickey32111** [comment]
When's the last time you did a git pull

**Comment by nborrmann** [comment]
delete the db or remove those pokemon manually using sql

**Comment by TheHippo** [comment]
> I have checked if this issue already exists (both open and closed issues)

I don't think so @janw-oostendorp:

* #278
* #274
* #271
* #260
* #262

**Comment by Mickey32111** [comment]
@TheHippo Let's not tease 😜
