### ISSUE TITLE
Pokemon Latitude/Longitude

### ISSUE THREAD

**Issue by JohnnyOmm** [favll/pogom#29]
what's the quickest way to get the pokemons latitude and longitude so I can move there with pokebot?

I click "get direction" under any pokemon and my latitude is always stuck at -0.000001

[http://prntscr.com/by0k0g](url)

**Comment by favll** [comment]
Are you using the most recent version? We recently fixed a bug that could be responsible for this.

**Comment by JohnnyOmm** [comment]
I redownloaded everything and installed requirements but now getting this error when  i open localhost:5000
"Oops! Something went wrong.
This page didn't load Google Maps correctly. See the JavaScript console for technical details."

**Comment by favll** [comment]
Have you put your Google Maps API Key into the `pogom/__init__.py` file?

**Comment by JohnnyOmm** [comment]
ya i tried 2 different keys one for browser and another for server

**Comment by favll** [comment]
Can you post an image of your JS Console?

**Comment by JohnnyOmm** [comment]
ahh nvm I had to create a brand new google account and new api. they old one wouldnt work. thanks for help!
