### ISSUE TITLE
[Question] vpn

### ISSUE THREAD

**Issue by labaland** [favll/pogom#290]
I run pogo map on my windows pc.
Without vpn i can connect to it from any public ip. And with my vpn on i cant. Only from the local ip.
Ports are open on my router and vpn service! Is it possible to make it work?
Sry bad english :)

**Comment by djv2** [comment]
1. this has nothing to do with this map. you are asking a network topology question, so you should not be asking here
2. that is normal and expected behavior, so nothing is wrong
3. try https://ngrok.com/

**Comment by labaland** [comment]
sry then! ngrok does not work when im on vpn either :(

**Comment by djv2** [comment]
for the record - i just tested ngrok + VPN and it works fine. something is wrong with your computer or network, but again this is not the place for this discussion
