### ISSUE TITLE
Where and how to host this app ?

### ISSUE THREAD

**Issue by EnigmaDay1** [favll/pogom#292]
## Checklist
 - [X] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [X] I have checked if this issue already exists (both open and closed issues)
 - [X] I am using the most recent version of pogom from the master branch
 - [X] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [X] I'm posting the complete log
 - [X] I'm using a descriptive title for this issue

## My Issue

Hello, I'm a beginner and I have a question, I do well the installation to use the application in my network only and it works.
But i'm wondering if it's possible to use this app when I'm outside with my 3G/4G.

I first think to use a VPN but it will be my last solution (I never use it one before).
I tried to upload with heroku but there is an error.

So, do you have an idea to where and how can I use this app outside ?

In advance, thanks.

**Comment by Cromi38** [comment]
Try ngrok, works perfect for me

**Comment by CuRleGit** [comment]
@Cromi38 
Does this work any better than just forwarding a port on your router?

**Comment by Cromi38** [comment]
@cuRlegit, so far yes it has worked better for me.
