### ISSUE TITLE
disappear time fix.. not working?

### ISSUE THREAD

**Issue by mwaraya** [favll/pogom#294]
its look like the "disappear time fix" its not working? https://github.com/favll/pogom/commit/a219d550a0050c6e57d9fb6d2a132211db83ef7d

i have severals icons, on top of each others, with +500 hrs disappear time... and here are others reports of this: https://www.reddit.com/r/pokemongodev/comments/4wqidn/pogom_is_back_with_the_fastest_map_available/?sort=new

maybe is a regional setting/format thing? im from latin america.

Thanks!

**Comment by kamieniarz** [comment]
I actually see no new pokemons with 500h+ but I still see old from before fix ;/

**Comment by Mickey32111** [comment]
@kamieniarz Drop your database or run a SQL query to remove them. (To drop just delete the .db file in your pogom directory)

**Comment by Mickey32111** [comment]
@mwaraya did you do the same? The fix does not remove existing long spawn pokemon from before the fix from the database so they'll still remain on the map

**Comment by nborrmann** [comment]
Dupe
