### ISSUE TITLE
Add a deploy button in the README.md

### ISSUE THREAD

**Issue by dreadpiratejhonatan** [favll/pogom#295]
## Checklist
 - [x] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [x] I have checked if this issue already exists (both open and closed issues)
 - [ ] I am using the most recent version of pogom from the master branch
 - [ ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ ] I'm posting the complete log
 - [x] I'm using a descriptive title for this issue

## My Issue

Hi, folks. I was wondering if you could add a deploy button in the README.md to automatically set up the map on a cloud host. Thanks.

**Comment by dreadpiratejhonatan** [comment]
@nborrmann If you give me some basic help, i think i can implement this feature. I spent all night searching for a way to deploy this on a platform like Jelastic, Scalingo or PythonAnywhere, but turns out i get nothing. I mean, the pogom is great and works fine on localhost (and it's incredible fast!) but i really want to learn how to (and) set this online!

**Comment by nborrmann** [comment]
Never done that, sorry.

**Comment by dreadpiratejhonatan** [comment]
Finally I got it! I've deployed it to Jelastic and now i can run it in a web server independently from the localhost. If you want, i can try dev this feature later. :D

**Comment by zordel** [comment]
Can you describe what you did? Would love to have it on cloud as well. Thanks!

**Comment by compuguy** [comment]
@dreadpiratejhonatan If you can find a VPS host that isn't ip banned, you could deploy it as a docker container. I had it working with docker-compose with a nginx proxy.

**Comment by dreadpiratejhonatan** [comment]
@compuguy I've added a Deploy button to Jelastic (check it out on my fork), which instantaneously put the map on cloud. @nborrmann Would you like to Pull this?

**Comment by compuguy** [comment]
@dreadpiratejhonatan I'll take a look at it, but I still would like to continue working on the docker support for pogom.

**Comment by dreadpiratejhonatan** [comment]
@compuguy Why do you think it's not deploying properly? I was thinking it could be because the service provider the user choose.

**Comment by compuguy** [comment]
@dreadpiratejhonatan It depends on the service provider. Two of the north american hosts won't build the docker container. Webhosting.net does work, but I believe is ip blocked by niantic.

**Comment by dreadpiratejhonatan** [comment]
@compuguy Yeah, probably. I tested two service providers, one from Colombia and the other from Russia, and both worked fine.

**Comment by labaland** [comment]
What is Jelastic ? :)

**Comment by eugenio412** [comment]
I think we need a list of the working providers, mine gets banned so fast. But the jelastic idea is awesome

**Comment by dreadpiratejhonatan** [comment]
@nborrmann @compuguy Do you guys have any idea how could I run this on a shared host? I wanna run this so my friends can access it by going on a domain like pogom.myownurldomain.com, but without using Jelastic. I already use HostGator with an one year plan, so i'm looking to host it there.
