### ISSUE TITLE
If each scan is 70 meter, then why adding a new location must be 100 meter or more?

### ISSUE THREAD

**Issue by blueskybreeze** [favll/pogom#298]
Can the minimum new location radius be 70m instead of 100m?

Because each scan is 70m, then if 100m, then doesn't it require 2 or 3 or 4 scans to cover a 100m radius?  (I actually might only need 70m and that's all)

Also, can it show "Nearby" (Sightings) Pokemons?

Can a config be added, such as, if I don't need to scan every 10 seconds, but every 20 seconds... or a random number of seconds, such as every 20 to 30 seconds?

**Comment by nborrmann** [comment]
>Can the minimum new location radius be 70m instead of 100m?
>Because each scan is 70m, then if 100m, then doesn't it require 2 or 3 or 4 scans to cover a 100m radius? (I actually might only need 70m and that's all)
Actually we'd have to increase the minimum to 120. Everything between 70-120 will be misleading because it still scans only 70m and not the radius indicated on the map.

>Also, can it show "Nearby" (Sightings) Pokemons?
No

>Can a config be added, such as, if I don't need to scan every 10 seconds, but every 20 seconds... or a random number of seconds, such as every 20 to 30 seconds?
Issue already exists.

**Comment by SM411** [comment]
Radius is two times the diameter. If you just wanted to cover a narrow line you could use a spacing of 140m, but to get some width, e.g. the road, you need a bit closer spacing, like about 120m.
https://i.imgur.com/VsKpXlA.png

**Comment by nborrmann** [comment]
The circle that is drawn on the map is only an approximation of the actual coverage (a pretty bad one, on small radii).

The 100m minimum is probably a leftover from when the scan radius was at 100. But  I insist, that it should actually be 120, to prevent the issue of the bad approximation. And who actually wants to scan only a 70m radius?

**Comment by blueskybreeze** [comment]
does that mean, if the circle is only an approximation, then if I add 12 locations along the road, then I may miss something spot on the map?

Or how about, if the circle drawn on the map smaller than the real scan or bigger than the real scan?  If the circle drawn on the map is smaller than the real scan, then nothing will be missing... just that I will be adding circles closer than needed.

**Comment by nborrmann** [comment]
>does that mean, if the circle is only an approximation, then if I add 12 locations along the road, then I may miss something spot on the map?

yes

**Comment by blueskybreeze** [comment]
so does that mean if I draw 10 or 20 circles, each one 100m radius, and I think it covers the whole road (as seen on the map), even all the circles are overlapping, then in reality, I might be missing part of this road completely?

do you mean there is some fixed "center" for the circles, so that, if I have 2 circles that are 50m apart, they may "snap to" the exact same circle and so what I thought an "8" figure is in fact just a duplicated circle?
