### ISSUE TITLE
Could i get a tutorial.

### ISSUE THREAD

**Issue by cwliias** [favll/pogom#30]
I have no idea what to do...

**Comment by tonywu3** [comment]
https://www.youtube.com/watch?v=RJKAulPCkRI

Follow that. And read the instructions for the commands to run it.

**Comment by cwliias** [comment]
ty lovely sir

**Comment by cwliias** [comment]
Do i have to follow this every time i want to open it? or is it always going to be up on local host?

**Comment by tonywu3** [comment]
You're always going to have to open up cmd and run that runserver.py line. If you know how to write scripts, there's ways to do it easily. 

Alternatively you can use the more popular version and just type "runserver.py -se" and it will use the settings in \config\config.ini 

https://github.com/AHAAAAAAA/PokemonGo-Map
