### ISSUE TITLE
"Back to map" not working

### ISSUE THREAD

**Issue by riccardonuzz** [favll/pogom#304]
## Checklist
 - [ ] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [ ] I have checked if this issue already exists (both open and closed issues)
 - [ ] I am using the most recent version of pogom from the master branch
 - [ ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ ] I'm posting the complete log
 - [ ] I'm using a descriptive title for this issue

## My Issue
When I run the server, I set up the api key and then I push "submit" but nothin happens. It redirects me on the config panel again, what do I have to do?

**Comment by nborrmann** [comment]
enter account credentials.
