### ISSUE TITLE
If a scan is 70m, then how come 100m or 120m will take only 1 scan?

### ISSUE THREAD

**Issue by blueskybreeze** [favll/pogom#305]
This is related to:

https://github.com/favll/pogom/issues/298

So when we add a series of locations along a long road (which is about 1000m), should be just add about 10 locations that are 100m radius, or 8 or 9 locations that are 120m radius?

If one scan is only or 70m radius, how come it can cover 100m or 120m?

**Comment by nborrmann** [comment]
Please stick to the issues you already opened.
