### ISSUE TITLE
stats and notifications do not work on mobile (iOS)

### ISSUE THREAD

**Issue by RvV1979** [favll/pogom#306]
## Checklist
 - [x ] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [x ] I have checked if this issue already exists (both open and closed issues)
 - [x ] I am using the most recent version of pogom from the master branch
 - [ ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ ] I'm posting the complete log
 - [x ] I'm using a descriptive title for this issue

## My Issue
I am running the pogom server on a macbook and locally everything works fine. To make the site available from outside I am running ngrok to provide a tunnel to the local host. Using the tunnel locally in chrome works fine as well. 

However, when I use the tunnel on my iphone 6, the stats & notifications page does not register any change I make (i.e. I never get any notifications and when I reload the page all checks are removed). 

This happens on chrome as well as safari on iOS 9.3.4
...

**Comment by nborrmann** [comment]
Afaik iOS doesn't have browser notifications. Get a decent phone.
