### ISSUE TITLE
[REQUEST] can a CSV / log file be created?

### ISSUE THREAD

**Issue by blueskybreeze** [favll/pogom#307]
Can a CSV file be created, with something like:

`Gastly, 2016-08-10, 22:01:58, 37.773972, -122.431297`

which is the Pokemon, date, time, and altitude, longitude, so that we can later on, use Excel or any programs to check, whether something mostly show up at night, and mostly at which location?  It seems right now there is `pogom.db-wal` but not sure if it is some proprietary db info that might be harder to use.  If it is CSV then it is more universal.

**Comment by nborrmann** [comment]
It's sqlite format. I'm sure there are bindings for excel.
