### ISSUE TITLE
Can't place or remove any scan locations

### ISSUE THREAD

**Issue by jorgdebont** [favll/pogom#308]
## Checklist
 - [x] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [x] I have checked if this issue already exists (both open and closed issues)
 - [x] I am using the most recent version of pogom from the master branch
 - [ ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ ] I'm posting the complete log
 - [x] I'm using a descriptive title for this issue

## My Issue
Clicking on the map does not provide me with the option to place a new marker.
Clicking on a marker does not provide me the option to remove this marker.\
I was able to place and remove markers before.

I've used both google chrome and firefox, restarted server, rebooted VM.
...

**Comment by nborrmann** [comment]
You need to login.

**Comment by jorgdebont** [comment]
Holy shit I'm a retard.
Thanks @nborrmann
