### ISSUE TITLE
Volume for notify

### ISSUE THREAD

**Issue by Cromi38** [favll/pogom#309]
Is there a way we can add a volume bar or something to make the notification sound higher or lower and possibly a mute button so only the notification pops up and there is no sound?

**Comment by nborrmann** [comment]
Use your browser or OS volume controls.

**Comment by Cromi38** [comment]
I still think it would be a useful QoL update... When you are running it for multiple people they don't all want to mess with browser settings, especially if they are using sound in browser already.
