### ISSUE TITLE
I added a auto start on pogom

### ISSUE THREAD

**Issue by Teamtyler2** [favll/pogom#314]
## Checklist
 - [x] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [x] I have checked if this issue already exists (both open and closed issues)
 - [ ] I am using the most recent version of pogom from the master branch
 - [ ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ ] I'm posting the complete log
 - [x] I'm using a descriptive title for this issue

## My Issue
Hey Guys,
I have created a file on my raspberry pi which auto matically starts the pogom direcotory (runserver.py)
if anyone wants it i will at a fork onto this page 
...

**Comment by favll** [comment]
Please use the issues tab only for issues :)

**Comment by Teamtyler2** [comment]
Woops sorry
