### ISSUE TITLE
The notify list is a localstorage, so if you change browser, or use localhost vs 127.0.0.1 vs 0.0.0.0 or a different port, then the notify list needs to be recreated

### ISSUE THREAD

**Issue by blueskybreeze** [favll/pogom#315]
In these cases, the notify list needs to be recreated.

I need that because I have localhost:5001 scanning a different area, and localhost:8000 scanning another area.

And then, Google Chrome's notifications will show and "disappear forever", and cannot be displayed for the past history. Safari (on a Mac) notifications can be shown for the past history, so I can see what happened for the past 8 hours while I was sleeping.  But if I use Safari, then I need to recreate the notify list again.

I copied and pasted the array in the dev tool instead of going through the list of 150 Pokemons... but still...

Maybe it can be part of the db, just like the areas (the regions added for scanning), so it will stay with the server / project.

**Comment by lax20attack** [comment]
It's not possible to share local storage across ports, even on the same domain.

For the majority of users, server side hiding would not be beneficial.

Maybe an option to do both server side and client side would be ok.

**Comment by compuguy** [comment]
@blueskybreeze You could just roll a front end nginx reverse proxy, and have different hostnames go to different ports.

**Comment by blueskybreeze** [comment]
but I suppose if you set up a server for your coworkers or family member for a nearby spot, then the "notify list" that is part of the server will not work because then you will need it have a user / login for a per user basis.

**Comment by nborrmann** [comment]
You have to config on every client. We don't intend to change that.

**Comment by nborrmann** [comment]
You have to config on every client. We don't intend to change that.
