### ISSUE TITLE
[Discussion] Optimal worker number and uptime in order not to be softbanned

### ISSUE THREAD

**Issue by Faskill** [favll/pogom#318]
Hello,

I've started to receive more and more softbans recently.
Before I was scanning all the time with 200+ workers but right now after a few hours (or even less) I just receive empty packets, I scaled it down to 65 workers and still the same thing..

Right now I'm using 49 workers (I just supposed 50 was the limit) with 30 minutes down time every 4 hours (my sh script is not pretty since I'm not a programmer but basically I have a sleep 14400 in it after which i taskkill python.exe and sleep 1800 before launching the server again) and it's working pretty well with no other downtimes. I'm scanning a 2.5km radius circle.

I was wondering if some of you had similar "strategies" and what do you think is the optimal amount of worker/uptime to scan areas as quick as possible without getting softbanned

**Comment by nborrmann** [comment]
My "strategy": 400 accounts, default settings. Working like a charm.

**Comment by Sociopaat** [comment]
I started with 10 accs but 7 of them get banned in 2-3 days
Then i did 8 accs same happens almost all banned after 2-3 days
Now im running 7 accs also 4 of them got banned yesterday

**Comment by xdemoor** [comment]
25 acc, 50% are banned after few hours. Two VPS IP banned in 24h.

**Comment by Faskill** [comment]
To all those who are receiving Account/Ip bans/softbans with a low number of workers, I encourage you to try to set up a downtime every 4-5 hours, it's working pretty nice for me.

@nborrmann How does the system handle a very high number of accounts? Is there a point at which your scan rate doesn't increase (depending on the size of the area you scan) but your delay between scans on the same account increases?

**Comment by nborrmann** [comment]
> does the system handle a very high number of accounts? Is there a point at which your scan rate doesn't increase (depending on the size of the area you scan) but your delay between scans on the same account increases?

Yes. At some point (depending on your system) you aren't bottlenecked by the number of accounts, but by networking and database. The program still rotates through all accounts, so the delay for a each single account increases.

**Comment by Bizadon** [comment]
@Faskill How we can set up downtime? Is now any working ptc account creators?

**Comment by eugenio412** [comment]
You are lucky @nb

**Comment by lisandro52** [comment]
@Bizadon It occurs to me that you can put "to sleep" your Scanner after certain hour. For example, if 10 AM > time.time() > 9 AM (current time is between 9AM and 10AM), do a `time.sleep(x)` with whatever you want (3 hours, 4 hours, etc).
With 200 accounts, @nborrmann is probably having a really long time between two requests from the same account, and that's helping him fool the banning system or whatever is doing the bans.

**Comment by PhDeez** [comment]
How are you guys determining bans?  I've had 10 accounts working well on a 1200m radius (3 workers) for more than a week now.  Is it the message about being rate-limited or the error 3?  Unfortunately, I didn't create my 100s of accounts before the recaptcha implementation since I was using the "other" map.

I will say that I logged all 10 of the accounts into PokeGo on a device that was not my main device , caught the 1st monster and gave them a Nickname (which happened to be the name of the PTC account).  I will also add that I shutdown the map scanning at night from ~11p-8a, but during the day it's just running non-stop...  A full scan only takes about 6 minutes so the lowest amount of time I have to get to a destination is ~8 minutes,

**Comment by eugenio412** [comment]
I guess it depends on the location, if you are using a IP known to Niantic the limit to the ban is much easier to be reached. In my VPS with 15 accounts I'm not having any ban using it 24/7, but in my jelastic even with 10 accounts i get banned in 15 minutes

**Comment by Mickey32111** [comment]
I used to get IP bans and account bans within 15 minutes, I reduced my workers to 25 and reduced my scan radius and I haven't received a single ban in around 12 hours.

**Comment by gideonfisk** [comment]
200 & 400 accounts! Creating google accounts is a painful process and I seem to be limited (stupid phone verification).

How have folks gotten hold of so many accounts? I'd love to be able to throw that many accounts at my scanner.

**Comment by Faskill** [comment]
Because we don't create google accounts, only ptc accounts

**Comment by NHLGames** [comment]
Is there a working account creator that can get around CAPTCHA? I used to have 200 accounts but they are gradually getting banned.  While I can create accounts fairly quickly manually, it is still a tedious process.

**Comment by Teamtyler2** [comment]
How do u set up the timer on pogom i got 25 account banned yesterday and im doing 45

**Comment by gideonfisk** [comment]
@Faskill Duh! Of course. 400 is still a lot but not quite so crazy impressive now, lol. Thank you!

**Comment by acastle16** [comment]
Current setup: 205 accounts, 1755 locations (spread out among many location circles), and a full scan takes ~2 minutes and 15 seconds. I changed line 103 in scan.py to: time.sleep(200) and line 122 to: time.sleep(100). Everything is working great just a few rate-limited's but I'm pretty sure it's just from empty spaces.

I'm not a programmer though so I was hoping that someone could please explain what those two values mean and what each one affects. My goal was to slow down the speed to prevent soft bans but I'm not sure if I did that right.

**Comment by StrykZ** [comment]
@acastle16 

this first timer determines how long to wait before starting the next scan, the code below is what i'm using, once it's at 100% it will wait 2 minutes before starting again

`while not self.api.is_work_queue_empty(): # Location change if self.scan_config.RESTART: log.info("Restarting scan") self.api.empty_work_queue() else: time.sleep(120)`

the second timer im not sure but i set mine to 120 and it seems every scan from 0-100% takes 2mins now, need to experiment some more with that later

---

there is a new semi automatic way to creating accounts, you need to do the reCaptcha manually tho

https://github.com/skvvv/pikapy

together with this batch file i made, creating accounts is a breeze now

`@echo off
set /P Username=Enter desired username: 
set /P Password=Enter desired Password: 
set /P LoopStart=Start loop at: 
set /P Loops=Times to loop: 

@set /a Loop=%LoopStart%+%Loops%

echo.

for /l %%x in (%LoopStart%, 1, %Loop%) do (
	
	echo.
	echo Creating account %Username%%%x
	echo.
	
	pikapy --username=%Username%%%x --password=%Password%

)

pause`

**Comment by PhDeez** [comment]
@acastle16 @StrykZ 
Looking at the second timer
```
            if (not self.scan_config.SCAN_LOCATIONS or
                    not config.get('ACCOUNTS', None)):
                time.sleep(5)
                continue
```
 it /looks/ like the time.sleep(5) is if there were any account configuration changes.  If there haven't been any changes then it won't utilize that value.  You could give it a try by removing an account from your account list and see if the scan restarts in 100 s instead of 5.

What I would like to find is where it makes each account wait 10 seconds before scanning again- I'd like to be able to adjust that.
