### ISSUE TITLE
Maps doesn't load on mobile devices

### ISSUE THREAD

**Issue by peeejayz** [favll/pogom#32]
Hi,

Loving this, but the map doesn't load on a mobile device. Works fine on desktop browsers, even trying to load desktop version of the site on the phone doesn't work.

I have tried this on Safari and Chrome on an iphone.

Many thanks.

**Comment by omidzargham** [comment]
I reported this exact issue already in issue #19, the problem comes from the let statement on map.js:2

**Comment by nborrmann** [comment]
dupe of #19
