### ISSUE TITLE
Nothing (freeze, loop) after runserver

### ISSUE THREAD

**Issue by N3x0n11** [favll/pogom#320]
## Checklist
 - [ x ] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [ x ] I have checked if this issue already exists (both open and closed issues)
 - [ x ] I am using the most recent version of pogom from the master branch
 - [ x ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ x ] I'm posting the complete log
 - [ x ] I'm using a descriptive title for this issue

## My Issue

Similar to this issue [223](https://github.com/favll/pogom/issues/223). 

Server was running successfully for days!
Then I had to kill the process it and suddenly this happens: I started it as usual using 
```
python runserver.py -H "0.0.0.0" -P 5001
```
and then if freezes, showing this message
```
2016-08-17 17:13:49,809 [     pgoapi] [   INFO] pgoapi v1.1.7 - Copyright (c) 2016 tjado <https://github.com/tejado>
```

I tried using 
- sudo
- python2.7 instead of python
- 127.0.0.1 after -H
- direct IP after -H
- restart
- different port
- reinstall everything in a totaly new ubuntu VM

Still the same. 

It is running in a Virtual Box 64 Ubuntu 16.04.1 LTS

**Comment by iMagooo** [comment]
Enable debug logs and see if that shows any other problems.

**Comment by N3x0n11** [comment]
Just started working again, ghost in the machine. Thanks anyway!
