### ISSUE TITLE
Possibly rate-limited?

### ISSUE THREAD

**Issue by hollingsbee** [favll/pogom#321]
hi i keep getting this on my scan at the moment. im using 25 accounts on it

**Comment by Dab-Nation** [comment]
its fine. Nothing to worry about. I have it on mine and my scan keeps scanning quick and i had 22 accounts. 

Now i'm getting a message saying log in failed... trying again in 5 minutes as a security precaution

havent a clue what to do now!

**Comment by favll** [comment]
Please read the FAQ in the README
