### ISSUE TITLE
Despawning pokemon occasionally trigger false positive respawn in same location

### ISSUE THREAD

**Issue by studiomayhem** [favll/pogom#323]
## Checklist
 - [x] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [x] I have checked if this issue already exists (both open and closed issues)
 - [x] I am using the most recent version of pogom from the master branch
 - [ ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ ] I'm posting the complete log
 - [x] I'm using a descriptive title for this issue

## My Issue

This has happened to me twice. A pokemon will appear on the map scanner and I will go out to collect it. Soon after the pokemon spawn timer expires, the map scanner will notify me again that a pokemon of the exact same type has spawned with a new timer in the exact same location. However, when I return to the location, there is nothing to be found. Could this be a misinterpretation of stale data?

**Comment by nborrmann** [comment]
Could be a double spawn.

**Comment by studiomayhem** [comment]
I thought it was a legit spawn, so I physically went back to the spawn location to search for the double spawn and it never showed up in either Sightings or in the game itself. It only showed up on the map.

**Comment by nborrmann** [comment]
Double spawns have the same encounter id. They don't show up the second time, if you've caught it during the first spawn.

**Comment by PhDeez** [comment]
I've seen this in the past - back when PokeVision was operational.

**Comment by Markx85** [comment]
Is it possible that it's just 30 minutes spawn?

**Comment by favll** [comment]
#350
