### ISSUE TITLE
History view

### ISSUE THREAD

**Issue by amra** [favll/pogom#326]
Add history view of spawns. I would like to try to predict when and where the next spawn will be.

**Comment by Korzakov** [comment]
Agree on this, it would be nice to have stats more like PokemonGo-Map. 
So you select a Pokemon (maybe with a filter on period like today, last x days, last month, lifetime) from the stats and view the spawnpoints with data like coordinates, spawntimes.
Also a "Last seen" column on the stats page would be nice.

**Comment by favll** [comment]
#390
