### ISSUE TITLE
Feature request - sending location via bot 

### ISSUE THREAD

**Issue by dawie180** [favll/pogom#328]
Some guys have created an awsome telegram bot which scans the database and notifies you with the name, location and dissapear time of a preselected list of pokemon if they appear.  Theres one feature needed which would allow us to go pokehunting  without ever needing to touch the PC where the server is running on, and thats to allow us to send our location to the telegram bot which then changes the scan location  of the server.  At the monent when out pokehunting i have  teamviewer in to my PC to change the location.  Sending the location via the bot will be a game changer.  TIA

**Comment by Teamtyler2** [comment]
Where is this video @dawie180

**Comment by dawie180** [comment]
Which video?

**Comment by Teamtyler2** [comment]
Where did you find your information from @dawie180

**Comment by dawie180** [comment]
The telegram bot is actually part of this project now, if u look in the readme it says now with Pogobot, which is a script someone else created and works like a charm.

**Comment by Teamtyler2** [comment]
@dawie180 Where is it i cant see it and i need to create one

**Comment by dawie180** [comment]
https://github.com/eugenio412/PogomBOT

**Comment by PhDeez** [comment]
I cross-posted this over on PogomBOT since I think that team needs to accept a location and radius (via telegram, or whatever is sending data to the client), then the pogom team needs a way to take in that data as I'm not sure how it would be possible now...

**Comment by SM411** [comment]
What you really should look into is port forwarding your bot web page such that you can access it over the internet and view the map and add/edit locations from your phone.

**Comment by dawie180** [comment]
@SM411 - Thanks, got ngrok working with ease.

**Comment by favll** [comment]
:+1:
