### ISSUE TITLE
How to acces to the Pogomap anywhere?

### ISSUE THREAD

**Issue by EiTeR94** [favll/pogom#33]
Hi,

Just wanted to know if that is possible to acces to the pogomap who run on my PC from my phone? 
It's only on localhost ?

**Comment by nborrmann** [comment]
The PokemonGo-Map guys have some info on that.
https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/How-to-make-your-map-available-externally

**Comment by EiTeR94** [comment]
Well NVM i find how to, with Ngrok .
Is it possible to change the sleep time?
