### ISSUE TITLE
Can't drop or modify pins on iOS devices

### ISSUE THREAD

**Issue by taknology** [favll/pogom#333]
## Checklista
 - [ X] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [X ] I have checked if this issue already exists (both open and closed issues)
 - [X ] I am using the most recent version of pogom from the master branch
 - [ ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ ] I'm posting the complete log
 - [X ] I'm using a descriptive title for this issue

## My Issue
When viewing the map on an iOS device I am unable to add, delete or modify any pins.

**Comment by PhDeez** [comment]
Are you logged in?  Without going to the "Server Configuration" page (and entering the password) you are unable to modify the pin locations.

**Comment by taknology** [comment]
Perfect!  Thanks!  It’s working now.

Thanks
Tony
