### ISSUE TITLE
Pokemon added to database on scan but not displayed on map

### ISSUE THREAD

**Issue by taknology** [favll/pogom#338]
## Checklist
 - [X ] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [X ] I have checked if this issue already exists (both open and closed issues)
 - [X ] I am using the most recent version of pogom from the master branch
 - [ ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ ] I'm posting the complete log
 - [X ] I'm using a descriptive title for this issue

## My Issue

Hello, I am running the server and it is not logging any errors. Gyms are displayed on the map, and even updated as the team changes, but pokemon are not. I checked the database and pokemon are indeed being added to the database, but they are not displaying on the map. This was running last night perfectly fine with pokemon displaying on map correctly. I have tested in Chrome, Safari and Mobile Safari.

**Comment by taknology** [comment]
So I dug into this a little deeper. It appears the pokemon data is being sent to the browser and added to the heatMapData array. The problem is they are not being displayed on the map. Is this an access issue getting to the icons on the server?

**Comment by nborrmann** [comment]
What happens when you access `/map-data`? Have you checked pokemon in the sidebar?

**Comment by taknology** [comment]
When looking at side bar do you mean the statistics in the menu?  It shows found Pokemon. I also look directly at the database and can see it getting updated with Pokemon. I also see the JSON data for he Pokemon being added to the heatMapData array. Which is weird because when I access /map-data it only has what looks like gyms in it.

**Comment by taknology** [comment]
UPDATE. This problem is resolved. After looking at the code that gets the Pokemon from the database and checking the time comparison, I realized the server had the wrong time set. All is good now.

**Comment by ratfish4life** [comment]
I'm getting the same problem as well, its scanning but no pokemon are showing up. What exactly did you do (in steps) to fix this?

**Comment by hue3b** [comment]
I'm also curious about how you solved it @taknology. I'm facing the same problem running from my pc.

**Comment by taknology** [comment]
The problem I was having was the server time was not set correctly. The query in the server that decides which pokemon to send in data to the browser does a time comparison. You need to make sure you timezone is set correctly (to whatever timezone you are in) and that the clock is set to the correct time for that time zone.

**Comment by hue3b** [comment]
UPDATE. I've solved my problem deleting the database files from my repo and starting the app again.
