### ISSUE TITLE
Question about overlapping locations

### ISSUE THREAD

**Issue by Korzakov** [favll/pogom#339]
## Checklist
 - [x] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [x] I have checked if this issue already exists (both open and closed issues)
 - [ ] I am using the most recent version of pogom from the master branch
 - [ ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ ] I'm posting the complete log
 - [x] I'm using a descriptive title for this issue

I have setup my scanning locations with some overlap. Does this mean the scanner will double scan these overlapping locations (process both circles) or is this is not an issue?

**Comment by nborrmann** [comment]
Yes, it will double scan.
