### ISSUE TITLE
Stats not correct, not using distinct on encounter_id

### ISSUE THREAD

**Issue by Korzakov** [favll/pogom#340]
## Checklist
 - [x] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [x] I have checked if this issue already exists (both open and closed issues)
 - [x] I am using the most recent version of pogom from the master branch
 - [x] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ ] I'm posting the complete log
 - [x] I'm using a descriptive title for this issue

I was looking at the stats and thought about the numbers of some pokemon. It seems the stats doesn't  use a select distinct on the encounter_id. This way pokemon with the same encounter_id, but with multiple disappear_time are all counted.

**Comment by nborrmann** [comment]
>It seems the stats doesn't use a select distinct on the encounter_id

It does.

>pokemon with the same encounter_id, but with multiple disappear_time are all counted

Those don't exist (except for double spawns) but it's the same pokemon so we don't want it twice in the db.

**Comment by Korzakov** [comment]
Ok, here are some screenshots of what I meant.

This was the first Snorlax, just popped in one hour ago. Has got a count of 18, and 18 rows in the database. All with the same encounter_id.
![database](https://cloud.githubusercontent.com/assets/21110690/17832888/eeb4d61e-670e-11e6-83fc-a97a33561b8b.PNG)
![stats](https://cloud.githubusercontent.com/assets/21110690/17832887/eeb40efa-670e-11e6-88c6-e501b9e0e8af.PNG)

**Comment by nborrmann** [comment]
Has been fixed, but you need to delete the pogom.db file for the changes to take effect.

**Comment by Korzakov** [comment]
Ok thanks for the reply. Was this mentioned somewhere? Didnt see any note about this. Guess I cant fix this with SQL script to save stats?
