### ISSUE TITLE
runserver.py: error: argument -k/--gmaps-key is required

### ISSUE THREAD

**Issue by weizh888** [favll/pogom#346]
I have both python 2.7 and 3.5 installed on my windows operating system. The default PATH is python 3.5, but I was able to finally install pip into the python 2.7 folder, and successfully ran pip install -r requirements.txt (actually ran: py -2 -m pip install -r requirements.txt). It succeeded.
In the last step: I ran C:\Python27\python runserver.py, and it gave the error as the title. Could anyone help to resolve the issue? Thanks a lot.

**Comment by Made123** [comment]
you set a gmap key on config server

**Comment by StrykZ** [comment]
From what he has written i dont think he can even launch the server let alone set the gmap key

Do you have a config.json file?
Might need to manually create one 

Make a text document, rename it config.json, open it and enter following and save

{"LOCALE": "en", "CONFIG_PASSWORD": "", "ACCOUNTS": [], "SCAN_LOCATIONS": [], "GOOGLEMAPS_KEY": "PUT YOU GOOGLE API KEY HERE"}

good luck

**Comment by weizh888** [comment]
@Made123 I did try to input the key in command, but it then gave another error, which requires to set the account, password, and locations
@StrykZ Thank you for the response. You're right. I don't find the config.json file. After adding the map key in command, it required further about the account, password, and locations. These should be input in the opened link normally, but it didn't do that way. There should be some function or program that didn't work correctly. Still hope to solve the issue, but I'll also try to manually create the file.

**Comment by SumBeam** [comment]
This project doesn't use the -k or --gmaps-key command attribute. Every setting is web-based

The project https://github.com/PokemonGoMap/PokemonGo-Map does use it, maybe you are trying to run that project instead of this one?

**Comment by weizh888** [comment]
@SumBeam I am running this project, not the other one. As @StrykZ mentioned before, there was some difficulty for the program to create a config.json file automatically, which is the reason that it asked me to input in the command. Still thank for your reply here.

**Comment by weizh888** [comment]
@Made123 @SumBeam @StrykZ Guys, I am so sorry that, I didn't run the right program, and do thank @SumBeam for the reminder of different program I was using. Now I am running it well! Thank you so much!
