### ISSUE TITLE
unable to detect pokemons come from pokeshops opening INSENSE.

### ISSUE THREAD

**Issue by Guile3home** [favll/pogom#347]
as far as i observe, time expired of those pokemons come from pokeshops in opening INSENCE are about 2 min  only.  other famous scanner (skxxagged) sometimes can detect them(not all). However,  i have put almost 70 workers to scan such pokeshops in a small area but it is still unable to detect those pokemons come from INSENCE.  is that a bug?  or any particular issues created by Nitanic that we still don't know?

**Comment by PhDeez** [comment]
1) I believe it's Incense
2) Incense is a local only thing to your character walking around
3) It sounds like you're actually thinking of Lure Modules which are applied to PokeStops and increase the spawn rate within a certain radius from it
4) I believe there was discussion on adding it... if it's not already added

**Comment by Guile3home** [comment]
thx for your remind.  it should be LURE MODULE, not insense.   i make a big mistake. issue closed.
