### ISSUE TITLE
Problem with loading pokemons

### ISSUE THREAD

**Issue by KubkeSVK** [favll/pogom#353]
## Checklist
 - [X] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [X] I have checked if this issue already exists (both open and closed issues)
 - [X] I am using the most recent version of pogom from the master branch
 - [ ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ ] I'm posting the complete log
 - [X] I'm using a descriptive title for this issue

## My Issue

Hello,
It worked without a problem 28 hours but after that time began to appear in the log pile mistakes map began to fall and cease to be displayed Pokémon. 
<img width="1680" alt="snimka obrazovky 2016-08-22 o 20 52 21" src="https://cloud.githubusercontent.com/assets/6685916/17867573/4c87a17a-68ab-11e6-89ee-dc7368c27dbc.png">
<img width="1680" alt="snimka obrazovky 2016-08-22 o 20 55 19" src="https://cloud.githubusercontent.com/assets/6685916/17867574/4ca7a358-68ab-11e6-89bc-d8fa539959a7.png">

Map running on
Ubuntu 16.04.1 LTS
pip 8.1.2 from /usr/local/lib/python2.7/dist-packages (python 2.7)
Python 2.7.12

**Comment by SumBeam** [comment]
Looks like your database file is corrupt. Could you rename your pogom.db file to pogom-backup.db or something and try again?

**Comment by KubkeSVK** [comment]
I have tried to delete a file pogom.db, I also tried to use the connection to the MySQL database and the problem persists.
