### ISSUE TITLE
ImportError: No module named 'flask'

### ISSUE THREAD

**Issue by EnigmaDay1** [favll/pogom#356]
## Checklist
 - [X] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [X] I have checked if this issue already exists (both open and closed issues)
 - [X] I am using the most recent version of pogom from the master branch
 - [X] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [X] I'm posting the complete log
 - [X] I'm using a descriptive title for this issue

## My Issue

Hello,

The application was working but 1 hour ago, I restarted it and now, I've this error :

![bugmap](https://cloud.githubusercontent.com/assets/16022645/17890347/b5303e50-6935-11e6-8ee2-ffb36efe0adf.png)

I tried to reinstall it but the error persists.

In advance, thanks for help.

...

**Comment by EnigmaDay1** [comment]
Mmm, my bad, it's a problem with Python, I'll reinstall this one.

**Comment by Pharonax** [comment]
Make sure you are running it in a virtual environment if you previously had one.

**Comment by EnigmaDay1** [comment]
Before, I had python 2.7.x and I install new version of python 3.5 but now, I can't use this app due to this error.
