### ISSUE TITLE
Can't find pokémon

### ISSUE THREAD

**Issue by Pharonax** [favll/pogom#357]
## Checklist
 - [*] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [*] I have checked if this issue already exists (both open and closed issues)
 - [*] I am using the most recent version of pogom from the master branch
 - [*] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [*] I'm posting the complete log
 - [*] I'm using a descriptive title for this issue

## My Issue

Am I softbanned by Niantic or is this an other issue? Can't seem to find Pokémon anymore, just an empty map with scanning locations.

terminal output: 
http://i.imgur.com/3aMLTxr.png

**Comment by kobyys** [comment]
This is a soft ban. I get these more and more. Especially when scanning wider locations. I wonder if a solution could be found to have the same accounts scanning the same spots over and over and not have them move too far distances in a short time to avoid the movement based soft bans. Another thing i'd really like would be different accounts for different scanning areas to avoid this problem as well for multiple scanning regions.  If i scan a 800m area i merely ever get softbanned but as soon as i move up to 2 km i get softbanned almost instantaneously. I am using 30 Accounts.

Does anyone have an idea how to fix this?

**Comment by drrck82** [comment]
You are scanning too large of an area, this is detectable very easily.  You are softbanned and will need to stop making requests for a while.  I have had good success using 3 accounts and 3 workers on 4-5 locations of 300m each.  When you get beyond this its quite easy to determine the spiral scanning format in the data and get flagged.

**Comment by zambartas** [comment]
I'm not saying either of you two are wrong, he may very well be soft banned since every scan seems to return that error message.  I get these same messages when I have too small of an area to scan and when I open it up to more areas, they go away.  

Sometimes I might have 3 workers scanning a 300m radius, and when I open another adjacent 300m scan location, these messages go away entirely.
