### ISSUE TITLE
Can't delete scan location

### ISSUE THREAD

**Issue by hoidaan** [favll/pogom#358]
## Checklist
 - [ ] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [ ] I have checked if this issue already exists (both open and closed issues)
 - [ ] I am using the most recent version of pogom from the master branch
 - [ ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ ] I'm posting the complete log
 - [ ] I'm using a descriptive title for this issue

## My Issue

Can't delete scan location, when I click on the pin it doesn't show anything, 30 minutes ago this option was still there but when I deleted it it just came back to the same spot, like https://github.com/favll/pogom/issues/166. I restarted the server but still nothing, tried it in Chrome and Safari (desktop). When I do it in iPokeGO (iOS app) it looks like its deleted but when I restart the app it's still on the old location. 

Anyone? :)

**Comment by hoidaan** [comment]
Reinstalled it and now it works.

**Comment by iCiccio25** [comment]
How did you resolve?
