### ISSUE TITLE
Is there anyway of running this as a subdomain on apache? 

### ISSUE THREAD

**Issue by Craggles17** [favll/pogom#363]
Checklist
 - [ ] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [ ] I have checked if this issue already exists (both open and closed issues)
 - [ ] I am using the most recent version of pogom from the master branch
 - [ ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ ] I'm posting the complete log
 - [ ] I'm using a descriptive title for this issue

## My Issue

Is there anyway of running this as a subdomain on apache?  Mywebsite.com/pogom for instance?

Thanks 

Craig

**Comment by bonzei123** [comment]
Yes. I just Let my Fritz Box forward to my no-ip Adress. Pogom runs on my raspberry and is used by half my town in our local whatsapp group.

**Comment by ctr26** [comment]
port 5000 is blocked on the server I'm using. Trying to pip it through 80 essentially, but there is a wordpress site already there.

**Comment by favll** [comment]
@Craggles17 You should be able to run pogom on `127.0.0.1:SOME_PORT` and use ProxyPass in the VirtualHost configuration to run pogom on a subdomain.
@ctr26 you can specify a port by using the `-P` flag.
