### ISSUE TITLE
Problem with ngrok

### ISSUE THREAD

**Issue by DevilJulio** [favll/pogom#364]
## Checklist
 - [ ] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [ ] I have checked if this issue already exists (both open and closed issues)
 - [ ] I am using the most recent version of pogom from the master branch
 - [ ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ ] I'm posting the complete log
 - [ ] I'm using a descriptive title for this issue

## My Issue

I've always used ngrok until today. Now the map doesn't update automatically new pokemon if i don't use my wifi, but I have to refresh everytime. Does anyone know why?

**Comment by drrck82** [comment]
You exceeded the connection limit with ngrok likely.  You may have use port forwarding.
