### ISSUE TITLE
Question: If map returns empty data, does another worker re-scan it?

### ISSUE THREAD

**Issue by trippyhat** [favll/pogom#365]
Sometimes  a worker gets the warning `Received valid response but without any data. Possibly rate-limited?`. 

If this happens, does another worker immediate try to scan that area in the same scan iteration? That is, on the first run, is it possible to holes in the map that have not been scanned due to this warning?

I'm just wondering if areas need to be rescanned twice to get a complete picture, since Niantic has started to seriously block walkers.

**Comment by RMSInterject** [comment]
I don't think it scans that area twice due to that warning. That warning just means no pokemon were found in that scan location as far as I understand it. I could be wrong and if so please feel free to correct me.

**Comment by trippyhat** [comment]
Hm, pokemon would be one thing, but missing Gyms and Pokestops is a bit more concerning. With Niantic banning accounts willy nilly, I'm wondering if I have to rescan locations multiple times to get all the data.

**Comment by RMSInterject** [comment]
Pokestops? I thought pogom didn't support those yet?

**Comment by Made123** [comment]
![capture](https://cloud.githubusercontent.com/assets/20769733/18271111/c5b1f8a8-7430-11e6-9e1c-931680d666f0.JPG)

Really worried about scanning the areas...
I have 42 accounts.

**Comment by favll** [comment]
Duplicate. The location will be scanned again during the next full scan.
