### ISSUE TITLE
Error 2006: MySQL Server has gone away.

### ISSUE THREAD

**Issue by Illydth** [favll/pogom#366]
Error 2006:  MySQL server has gone away.
Unexpected error while parsing response.
Response Dict...

When running pogom against a MySQL database, i'm periodically receiving the error messages above.

The "Response Dict" has a bunch of stuff after it (probably a database record).

Any ideas?  Is this just normal?  Am I losing data?  I'm seeing SIGNIFICANTLY less pokemon / spawns on the map than I'm used to, but I don't know if they smoothed out the spawns or what...there just may not be as many mons in my neighborhood as their once were.

As to my setup:  I'm running MySQL and POGOM in two separate docker containers (Docker 1.12) in swarm mode with both connected to the same "network" (basically linked).  I know the Database is up and running and accessible to the POGOM container and have verified connectivity between the MySQL server and the POGOM server.
...

**Comment by favll** [comment]
Can you provide a log screenshot?

**Comment by Illydth** [comment]
@favll Actually I ended up restarting this and havn't seen the issue since.  Not sure what happened but apparently the POGOM container wasn't actually seeing the MySQL container so the error message was giving exactly what it was intending to give.  

You can go ahead and close this as either cancelled or solved, whichever you feel appropriate.
