### ISSUE TITLE
DB Logs show Future Date - Change Output Timezones

### ISSUE THREAD

**Issue by cdicey** [favll/pogom#367]
## Checklist
 - [x] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [x] I have checked if this issue already exists (both open and closed issues)
 - [x] I am using the most recent version of pogom from the master branch
 - [N/A] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [pieces] I'm posting the complete log
 - [x] I'm using a descriptive title for this issue

## My Issue

After saving pogom.db as a CSV via Sqlite, I opened the information in Excel. I noticed some of the disappearance times were for 8/25/2016. Some of the Disappearance times are more than an hour into 8/25, even though it was still the 8/24. Seeing as it was still about 11:45pm 8/24 and the last scan had been closed at least three hours earlier, I dug deeper. I have approximately 715 data entries under 8/25.

I have two screenshots, one of the DB in Sqlite and the other of the same information in CSV format/Excel. I'm including two sets of data so you can see it isn't just for a few select points.

Example 1:
a. Sqlite: ![image](https://cloud.githubusercontent.com/assets/21052513/17956806/70d0851e-6a5a-11e6-8356-16a8b31f8918.png)
b. CSV/Excel: ![image](https://cloud.githubusercontent.com/assets/21052513/17956971/d2911f06-6a5b-11e6-800d-53046080dbda.png)

Example 2:
a. Sqlite: ![image](https://cloud.githubusercontent.com/assets/21052513/17957036/5d5fd942-6a5c-11e6-978c-9653adb436ff.png)
b. CSV/Excel: 
![image](https://cloud.githubusercontent.com/assets/21052513/17957071/83836954-6a5c-11e6-9978-5e17d9dacea3.png)

The clock and date on my computer are correct. Is there some other clock or time codes potentially screwing up the data times? Is this clock run via Universal time/GMT? Has anyone else seen this? If you need more info or entire files, let me know. It's late, so hopefully I'm not overlooking something simple messing with this.

Thanks!

EDIT: Now I'm realizing it is more than likely on UTC time. Is there a way to fix this so the data shows up in our own timezone?

**Comment by favll** [comment]
Timestamps have to be saved in UTC to ensure multi user support, however, if you want to use a database dump for data analysis you can add or subtract hours via an sql query.
