### ISSUE TITLE
No map, no scan, no data return

### ISSUE THREAD

**Issue by poke4fun** [favll/pogom#370]
## Checklist
 - [x ] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [x ] I have checked if this issue already exists (both open and closed issues)
 - [ x] I am using the most recent version of pogom from the master branch
 - [ ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ x] I'm posting the complete log
 - [ ] I'm using a descriptive title for this issue

## My Issue
This is what I have when I run 

$ python runserver.py
2016-08-27 07:14:32,934 [     pgoapi] [   INFO] pgoapi v1.1.7 - Copyright (c) 2016 tjado <https://github.com/tejado>

That's all I received. I have been using it several days in the past, it suddenly stopped working. 
I tried to run a different computer with fresh installation of pogo, I had the same outcome. 
Possible problems and any suggestions to fix it? Thank you

...

**Comment by poke4fun** [comment]
Sorry, it now works for some reasons.

**Comment by todd-lm** [comment]
Hi, I am also getting this error, did you by chance follow any steps to fix this? Thanks! I can get to the config screen but the map won't load.
