### ISSUE TITLE
Problems accessing server from outside my network on OSX

### ISSUE THREAD

**Issue by KSUWildcatFan** [favll/pogom#372]
Everything is installed and working perfectly as far as the server goes. Scanning like a dream.

My issue is a Mac OSX (Yosemite 10.10.5) issue. I can't seem to access my map from my IP:5000/#.

I tried enabling sharing and still nothing. Anyone else run into these issues?

I was running the old pogo maps fine (the ones that "enabled sharing" and provided a URL), but I can't seem to get this one working outside my network.

**Comment by Mickey32111** [comment]
You either need to port forward or use ngrok (https://ngrok.com/)

**Comment by KSUWildcatFan** [comment]
Worked perfectly. Thanks @Mickey32111!
