### ISSUE TITLE
Mysql 

### ISSUE THREAD

**Issue by scopus-ru** [favll/pogom#374]
Tell me how to connect your database mysql 
I specify paratmetry
--db-type mysql --db-name pogo --db-user pogo --db-pass pogo18407506 --db-host 127.0.0.1 --db-port 3306
error: unrecognized arguments: --db-type mysql --db-name pogo --db-user pogo --db-pass pogo18407506 --db-host 127.0.0.1 --db-port 3306

**Comment by smartcuc** [comment]
As per documentation:
mysql://user_id:passwd@ip:port/db_name
Have fun!

**Comment by scopus-ru** [comment]
if not difficult to tell where to insert it exactly?

**Comment by Jordan-TE** [comment]
Optional: You can tell PoGoMap to use MySQL or PostgreSQL. You will need to install a python interface for the database system of your choice (i.e. pip install mysqlclient for MySQL or pip install psycopg2 for PostgreSQL). You will also need to specify the **--db flag** when starting runserver.py and pass it a valid database url string as specified in the Peewee docs.

**Comment by smartcuc** [comment]
python ./runserver.py -H 0.0.0.0 -P 5000 --db mysql://user_id:passwd@ip_addr:3306/db_name

**Comment by scopus-ru** [comment]
many thanks. Tell me you're planning to add support for pokestop?

**Comment by SumBeam** [comment]
You can use this pull request to add pokestops to your map: https://github.com/favll/pogom/pull/362
