### ISSUE TITLE
New Protos 0.35.0 implementation

### ISSUE THREAD

**Issue by darkeagl** [favll/pogom#376]
## Checklist
 - [x ] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [x ] I have checked if this issue already exists (both open and closed issues)
 - [ x] I am using the most recent version of pogom from the master branch
 - [ ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ ] I'm posting the complete log
 - x[ ] I'm using a descriptive title for this issue

## My Issue
This is not reall yan issue just a question.

Will you be updating the Protos section to the latest 0.35.0 ? It was released on the https://pogodev.org/ website. Just wondering before your awesome map isnt working. I am loving it :smiley: 
...

**Comment by daveyfong** [comment]
Looks like the 0.35.0 update is for buddy feature? Not really something important for a map?

**Comment by darkeagl** [comment]
Ok. I was just asking before workers get banned because using outdated protos.

**Comment by favll** [comment]
96db5a7eb30a4d6714c121609a09c6c537ae7273
