### ISSUE TITLE
How to run this map by cloud provider

### ISSUE THREAD

**Issue by ohnight8290** [favll/pogom#379]
## Checklist
 - [V ] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [ V] I have checked if this issue already exists (both open and closed issues)
 - [V ] I am using the most recent version of pogom from the master branch
 - [ ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ ] I'm posting the complete log
 - [V ] I'm using a descriptive title for this issue

## My Issue
I successfully setup the map yesterday, however, it is easy to get ip-banned by Niantic which makes my map unable to scan pokemon and I even cannot play the game at home. And I read the FAQ part, the cloud provider can be used to avoid ip-banning and ensure the map run properly. However, I don't even know what a cloud provider is...
Can anyone teach me how to use the cloud provider or send me a tutorial for newbie. It would be highly appreciated..

P.S. Is jelastic a cloud provider? I tried to use it but it is too difficult to me...
...

**Comment by xquiaz** [comment]
me too,  after success run "python runserver.py" nothing happen with the sub web.
scanner work perfectly.

*sudo is not allowed for jelastic. -______________-

**Comment by ohnight8290** [comment]
Please help..

**Comment by g-leclaire** [comment]
Here is a guide : https://www.reddit.com/r/pokemongodev/comments/4xy8p9/setting_up_easily_pogom_on_cloud/
Please note that cloud services are not free, but some cloud providers provide free trials.
