### ISSUE TITLE
Clear pokkemon with TIme remaining over 15 min

### ISSUE THREAD

**Issue by darkeagl** [favll/pogom#381]
## Checklist
 - [ x] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [ x] I have checked if this issue already exists (both open and closed issues)
 - [ x] I am using the most recent version of pogom from the master branch
 - [ x] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [ x] I'm posting the complete log
 - [ x] I'm using a descriptive title for this issue

## My Issue
Hello, I see pokemon with remaining time of over 100 hours. Is there a way to filter these out because this timespan is not possible? Would be very useful.

Thank you.
...

**Comment by Korzakov** [comment]
Stop the script, delete your pogom.db, and start script again. That creates a new db without these endless pokemon.
