### ISSUE TITLE
Inactive

### ISSUE THREAD

**Issue by qwerty0123** [favll/pogom#385]
Why have none of the pull requests, or issues been addressed or merged? Has this gone inactive? If you guys are just super busy it's fine, just tell people so we don't think this is dead

**Comment by djv2** [comment]
would like to know as well. this is great map, but support has disappeared from admins

**Comment by compuguy** [comment]
Agreed, this may be in part to the fact that they ip banned most VPS hosts/services. What this needs is the ability to add multiple proxies somehow.

**Comment by djv2** [comment]
@compuguy don't think so, i can get around the IP banning just fine. it's more or less as if the admins lost interest in pogo (as did many others)

**Comment by Mickey32111** [comment]
someone who is pretty code perficient and active wanna make a fork?

**Comment by favll** [comment]
Jup, I was on vacation. Back again since yesterday.

**Comment by Unknown66** [comment]
@favll welcome back hope your vacation was nice. Would be cool if you could tell us next time that you're gone for some days :)
