### ISSUE TITLE
Launch it on a server

### ISSUE THREAD

**Issue by VirAlex** [favll/pogom#404]
## Checklist
- [ ] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
- [ ] I have checked if this issue already exists (both open and closed issues)
- [ ] I am using the most recent version of pogom from the master branch
- [ ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
- [ ] I'm posting the complete log
- [ ] I'm using a descriptive title for this issue
## My Issue

Hello i have a question, I am a beginner i succeeded to launch the scrypt and notifications with telegram but i have a question is it possible to launch this on a server so as not to let it run computer? I search on the net but i didn't succeed 
Thank you
...

**Comment by smartcuc** [comment]
Well, I have it up and running on an simple PI (always on).

**Comment by darkeagl** [comment]
What parameters did you run it with, because I have to restart it every few hours after no response :(

**Comment by smartcuc** [comment]
Well, first of all, I'm using an PI 2 with USB stick. This is due to the mysql DB, otherwise, the SD card will be damaged within 1.5 days.

`python./runserver.py -H 0.0.0.0 -P 5000 --db mysql://db_user:db_password@localhost:3306/pogom &
`

It's now more then 4 weeks up and running without any issues.

**Comment by darkeagl** [comment]
Thanks, will try it later today :D

**Comment by jde1126** [comment]
Do you know if Ubuntu Server can reboot automatically?

Every once and awhile, so it can take a break.

**Comment by smartcuc** [comment]
Depends on the trigger / event you want to use. Via crontab it can be done e.g. every hour or x hour.

**Comment by M3G4THEKING** [comment]
You can creat a crontab for stop map and after some time restart.
