### ISSUE TITLE
Notification Needed on this Map ASAP

### ISSUE THREAD

**Issue by slimvaio** [favll/pogom#42]

**Comment by MarkusFlorian** [comment]
I redesigned the map and frontend to work for hosted solutions.

you cant change the center of the discovery radius any more but i added a "show only" filter, and a notification area customized for each individual visitor with notifications 

if this sounds what you need i can create a forked repo and provide the link

**Comment by nborrmann** [comment]
@MarkusFlorian Please do!

**Comment by MarkusFlorian** [comment]
@nborrmann  here you go
https://github.com/MarkusFlorian/pogom

we host it for scanns in Vienna and Wr Neustadt at pkmn_wrn.itdata.at or pkmn_wien.itdata.at

its the same scan you just start the map in differnt centers ;)

**Comment by MarkusFlorian** [comment]
@favll  are you interested in the changes to mapjs and maphtml ? if so i can make a pull request

**Comment by ritolika** [comment]
I made it compatible with chrome notifications and i'm working on pushbullet integration right now if anyone's interested

**Comment by casper-gh** [comment]
@ritolika interested in notification

**Comment by moggd** [comment]
@ritolika also interested

**Comment by Zyrixion** [comment]
@ritolika similarly interested, long as it produces some sort of audio cue since that's most useful to me.

**Comment by ritolika** [comment]
@casper-gh @moggd @Zyrixion I've done some good progress, I'll hopefully be finished tomorrow, and I'll link you to the download :)

sneak peak: https://gyazo.com/905ce5a649e177601471b3e900dca3b7

**Comment by omidzargham** [comment]
@ritolika Thank you very much for working on the notifications. However pushbullet has just announced it will limit pushes for free users to 500 per month for free users. Is it possible you change the service to telegram or something with unlimited pushes? Thanks!!

**Comment by ritolika** [comment]
@omidzargham I'll look at it tomorrow. I'm quite sure I could add telegram or something similar.

**Comment by omidzargham** [comment]
@ritolika Thanks! I don't know the details but I think slack, telegram, and facebook messenger are other alternatives, I'm not sure which ones have push limits / rate limits.

**Comment by casper-gh** [comment]
I like slack, not sure if they have cap on webhooks

**Comment by szeco** [comment]
also registering interest in chrome notification @ritolika

**Comment by ritolika** [comment]
@omidzargham @casper-gh @szeco @Zyrixion @moggd 

As there had to be a lot of options in the main page for the notifications I decided to write a new page just for the notification settings. So the notifications are a bit delayed. Just so you can get the most user friendly experience :+1:

**Comment by ritolika** [comment]
@nborrmann If yoy would like me to I could make this a pull request :)

**Comment by jasondinh** [comment]
Any updates on this? Pushbullet/Slack would be extremely helpful.

**Comment by MatyiFKBT** [comment]
@ritolika I'm interested in pushbullet, too!

**Comment by DavidSelem** [comment]
Pushbullet and Twitter please

**Comment by wilsonwc** [comment]
I've got a 5 minute hack version in this fork, if you look at the top of map.js you can find the static notification list (level 3 and non-evolvable pokemon).  https://github.com/wilsonwc/pogom

I'll clean it up and formalize it tonight with a selector box in the UI and then probably work on a simple slack webhook.

**Comment by nborrmann** [comment]
For selection, please use the /Stats page. Just add a checkbox for each Pokémon.

**Comment by wilsonwc** [comment]
Will do, what are your thoughts on starting with a pre-filled list of the high level pokemon like I have in my fork?

**Comment by nborrmann** [comment]
Yes, i had that in my mind. The rarest 50-70 or something.

**Comment by Clavus** [comment]
Eagerly awaiting those notification features (Chrome notifications mainly). It's the only thing I missed when moving over to this scanning solution :)

**Comment by wilsonwc** [comment]
Ok, Chrome notifications are ready to roll in my fork, a pull request has been submitted #195 for inclusion in the the main project.

**Comment by wilsonwc** [comment]
Merged, we can close this issue
