### ISSUE TITLE
Getting continuous string of errors saying: Received empty map_object response. Logging out and retrying.

### ISSUE THREAD

**Issue by todd-lm** [favll/pogom#420]
## Checklist
 - [X ] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [ X] I have checked if this issue already exists (both open and closed issues)
 - [X ] I am using the most recent version of pogom from the master branch
 - [x ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [X ] I'm posting the complete log
 - [ X] I'm using a descriptive title for this issue

## My Issue

Hi, so even though it says that getting this error is normal, I don't think it is working and its been saying this for about 20 mins: 

```
2017-04-29 15:58:41,516 [     pgoapi] [   INFO] Attempting login: Toddbot1
2017-04-29 15:58:41,942 [     pgoapi] [   INFO] Login successful: Toddbot1
2017-04-29 15:58:42,041 [     pgoapi] [   INFO] Received empty map_object response. Logging out and retrying.
```
Im using OS X and 1 bot, any help?

I see this repository hasn't been updated in a long time, is this working with gen2 and the newest Pokemon go client???!

**Comment by todd-lm** [comment]
@pixmaip @halorrr @SumBeam @nborrmann @ensingm2 @ @favll   #PLS HELP ME @ # # # # # # # #

**Comment by todd-lm** [comment]
NOOO

**Comment by luzannew** [comment]
This repo is no longer maintained... I switched to RocketMap.

**Comment by todd-lm** [comment]
Haha lol ok. I was just starting to set up rocket map as well.
