### ISSUE TITLE
[Suggestion] Remotely accessible "direct surroundings" scan

### ISSUE THREAD

**Issue by bas-stringer** [favll/pogom#43]
POGOM does a lot of things really well, but it's not very "mobile", in the sense that I can't access it while not in front of my desktop. I could of course forward the port and access my.ip:5000, but that still only gives me vision on the area it's set up to interrogate.

It happens to me fairly regularly that I'm walking or cycling somewhere I **haven't** configured POGOM to search, but something shiny shows up on my Nearby list. The footprint indicators being in the state that they are, chances of finding the shinies are slim at best.

What I'd like is a page which I can access from e.g. my cell phone, which:
1) gets my current location in one of several ways*
2) scans the ~200m around the position **once**, instead of continuously
3) overlays the locations of found pokemon (and their "expiration" time) on a map

How to get my current location:
Idea A) Take an initial guess based on the IP from which the request is sent, then refine from user input (click on the map)
Idea B) Creative use of recovery tools (e.g. through the Android Device Manager)
Idea C) Make a simple app that accesses the phone's internal Location API: configure it with your IP address, the correct port, your sniffer account credentials, and add a server-side @route hook to the Flask app for URL-based access.

Especially if the GPS data is sent/received through an app, it might even be desirable to set the center of a search radius to your position (+/- a randomized offset to make it harder to trace the sniffer account to your main based on overlapping location?) and have the scan "follow" you as you move...

Any interest in picking this up, or shall I see how far I get writing an ugly hack myself?

**Comment by Toliver182** [comment]
you can just tap the map and set that as the location to scan, works great on ios

set the -H paremeter to 0.0.0.0 and forward your ports and its usable everywhere

**Comment by bas-stringer** [comment]
@Toliver182 What about the "scanning only once" thing? Any way to make that fly with the code as-is?

**Comment by favll** [comment]
@bas-stringer Have you tried using the "tap on the map" feature? It seems like it could be what you are looking for? And I'm also not sure what you mean with "scanning only once"?

**Comment by nborrmann** [comment]
The newest version can do multiple locations.
