### ISSUE TITLE
Move to different proto engine

### ISSUE THREAD

**Issue by nborrmann** [favll/pogom#44]
Parsing the protobufs is a major bottleneck right now.

Google's python library is really slow. There are some alternatives, but the main problem seems to be that they are all hard to install, especially on windows. They usually require C/C++ compilers during installation. 

 - Switching the google python library to use c++ (see http://yz.mit.edu/wp/fast-native-c-protocol-buffers-from-python/) Also requires rebuilding from source.
 - https://github.com/bumptech/palm Got it to semi-run on linux. But couldn't install on windows. I have pushed some work to the different-proto-engine branch
 - https://github.com/Cue/fast-python-pb Only supports a limited subset (haven't checked if it would be sufficient)
 - https://github.com/connexio/cypb

Maybe someone knows more and can try some of the stuff.

**Comment by bas-stringer** [comment]
The python library Google provides comes with a C++ backend that's disabled by default, but delivers significant speedups if switched on (which may or may not be straightforward on different platforms). Even so, Pyrobuf claims to outperform it regardless:

https://github.com/appnexus/pyrobuf
http://techblog.appnexus.com/blog/2015/12/22/pyrobuf-a-faster-python-protobuf-library-written-in-cython/

It's hard to compare these alternatives in terms of performance or ease of deployment/distribution, but _pyrobuf_ appears to me as the most mature project of the bunch.

**Comment by nborrmann** [comment]
Thanks for the tip. I had a look at it, but it turns out:

 - It doesn't support nested types (https://github.com/appnexus/pyrobuf/issues/56)
 - It's hard to install on windows, as it needs cython and a c++ compiler
