### ISSUE TITLE
TypeError: invalid arguments to setopt

### ISSUE THREAD

**Issue by Readdeo** [favll/pogom#53]
After installing the dependencies, i still get this error on Fedora. http://pastebin.com/bYEKjXs9

**Comment by nborrmann** [comment]
Dunno if you know python, but you can try opening the file `pogom/pogom/pgoapi/rpc_api.py` and removing options from the dict `pycurl_options` in line 55 until it works.

Unfortunately I can't diagnose which one is causing the error from here.

**Comment by Readdeo** [comment]
7.29.0 is my libcurl, is it okay? Which specific libcurl file is needed for this?
I tried deleting the options, nothing has changed.

**Comment by nborrmann** [comment]
We actually resolved such an issue yesterday. Did you check out the newest version from the repo?

You need
```
sudo apt-get install libssl-dev libcurl4-openssl-dev python-dev
```

You can also try commenting this line:
```
            pycurl_options[pycurl.DNS_SERVERS] = "8.8.8.8"
```
