### ISSUE TITLE
Map Download Failed, happened since this morning

### ISSUE THREAD

**Issue by casper-gh** [favll/pogom#58]
Map was running good for me yesterday, but this morning when I checked again, there is no pokemon on the map. Check the log I see this:

```
2016-07-28 21:25:20,081 [     search] [   INFO] Attempting login
2016-07-28 21:25:20,082 [   auth_ptc] [   INFO] Login for: <REDACTED>
2016-07-28 21:25:20,506 [   auth_ptc] [   INFO] PTC Login successful
2016-07-28 21:25:20,845 [     search] [   INFO] Login successful
2016-07-28 21:25:20,845 [     search] [   INFO] Starting scan of 1945 locations
2016-07-28 21:25:30,850 [    rpc_api] [WARNING] Error downloading map: 0
2016-07-28 21:25:30,851 [     search] [   INFO] Map Download failed. Trying again.
2016-07-28 21:25:30,852 [    rpc_api] [WARNING] Error downloading map: 0
2016-07-28 21:25:30,852 [     search] [   INFO] Map Download failed. Trying again.
2016-07-28 21:25:30,853 [    rpc_api] [WARNING] Error downloading map: 0
2016-07-28 21:25:30,853 [     search] [   INFO] Map Download failed. Trying again.
2016-07-28 21:25:30,855 [    rpc_api] [WARNING] Error downloading map: 0
2016-07-28 21:25:30,855 [     search] [   INFO] Map Download failed. Trying again.
2016-07-28 21:25:30,856 [    rpc_api] [WARNING] Error downloading map: 0
```

Thanks for the fast map

**Comment by EiTeR94** [comment]
same issue

**Comment by nvhk** [comment]
the same

**Comment by nborrmann** [comment]
Google or PTC Account?

With or without -c?

What happens if you enable/disable -c?

**Comment by EiTeR94** [comment]
with/without -c same issue

**Comment by grisha0000** [comment]
Happening since this morning as well, -c doesnt work at all, without -c it works but gets traceback on half 1/3 of the scans, says something related to line 131 in search.py and line 110 in models.py

**Comment by casper-gh** [comment]
@nborrmann same error with/out `-c`

**Comment by casper-gh** [comment]
Check this out guys: (something got patched)

https://www.reddit.com/r/pokemongodev/comments/4v36h5/is_traffic_being_throttled/

**Comment by EiTeR94** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/2513

**Comment by nborrmann** [comment]
Can confirm this behaviour. Works fine when throttling to 1 per second.

... well, it was fun while it lasted.

**Comment by casper-gh** [comment]
can I use this flag here `-t 1 -sd 0.2` ?

**Comment by nborrmann** [comment]
@casper-gh No

**Comment by ddho23** [comment]
Is throttling implemented ?

**Comment by Zyrixion** [comment]
Same issue~

**Comment by favll** [comment]
Due to the throtteling the -c option does not work at the moment. We have released a hotfix so that you can use the map without the -c option. However, it will not be as fast as before. We are currently evaluating options to achieve higher scan speeds again.

**Comment by Zyrixion** [comment]
@favll threaded workers (using multiple accounts/apis) would be the primary idea to reach higher speeds, I should think.

**Comment by carze** [comment]
@Zyrixion guess it depends on whether or not throttling is based off IP or PTC/Google account. Though it'd be hard to believe Niantic would throttle off IP as you can have multiple people in the same household playing and it might cause issues there.

**Comment by NHLGames** [comment]
I am still getting errors even after the recent fix.

**Comment by carze** [comment]
Playing around with a multi-account implementation of PokemonGo-Map seems to be working well. If PoGoMap's pycurl method could somehow be adapted to use multiple accounts I think it could be just as good as before throttling kicked in.

**Comment by NHLGames** [comment]
Are you talking about this fork?
https://github.com/modrzew/pokeminer

**Comment by carze** [comment]
@NHLGames no this one https://github.com/shiona/PokemonGo-Map

**Comment by NHLGames** [comment]
Ah ok.  I just tried it, but I keep getting "Niantic's servers are under heavy load".  The previous version of pogom works the best for me (I get many errors in the console, but it still scans the fastest)

**Comment by favll** [comment]
The new Pogom version includes the Api fix.
