### ISSUE TITLE
Miss some pokemon

### ISSUE THREAD

**Issue by jfabrici** [favll/pogom#63]
Miss when i compared with pokevision
Some pidgey and zubat, nothing important but it can happen on rare

**Comment by nborrmann** [comment]
Please post your command line output. 

It's probably due to #58, closing for now.

**Comment by jfabrici** [comment]
No I didn't get error, but if i change the marker place the pokemon would appear, i suspect this is due to the change of the radius meter like some people say https://github.com/AHAAAAAAA/PokemonGo-Map/pull/2610/commits/f47ce459dba04d3a3890297fcdf138fe05f2d332

**Comment by nborrmann** [comment]
Yeah, they changed the scan radius. Just fixed this.
