### ISSUE TITLE
Login -> Retry Doesnt work 

### ISSUE THREAD

**Issue by jfabri63** [favll/pogom#69]
Sometime there is a login failed error but it always failed to reconnect.
The thing is that if you re run the server with python runserver.py -a google -u ...... it works directly

Here is the error : https://i.gyazo.com/1711ceeac51b3009ee4cb3df75a59074.png

**Comment by favll** [comment]
Should be fixed in the new pogom version (coming soon TM).

**Comment by favll** [comment]
The new version is out!
