### ISSUE TITLE
Linux App does not work

### ISSUE THREAD

**Issue by heipnotik** [favll/pogom#72]
Downloaded Lin.zip 
Tried to run on 16.04 
Does not run.....

**Comment by favll** [comment]
What do you mean by downloading lin.zip? Recommended installation instructions:

- `sudo apt-get install libssl-dev libcurl4-openssl-dev python-dev`
- git clone `https://github.com/favll/pogom.git`
- `pip install -r requirements.txt`
- enter your google maps api key in `pogom/__init__.py`
- `python runserver.py -u <user> -p <pass> -l "Location" -r <radius in meters>`
