### ISSUE TITLE
The encounter_id is not unique

### ISSUE THREAD

**Issue by pgodev** [favll/pogom#74]
On a medium-sized city, we are finding several existing encounter_ids each hour. These have different spawnpoint_ids and disappear_times, but the same encounter_id.

Since the disappear_times of the last encounter with this encounter_id is usually a few days ago, this is no problem for the live map. But for data mining purposes, deleting old encounters is not so nice.

We've fixed this by removing `primary_key=True` from the encounter_id CharField, and adding 

    class Meta:
        primary_key = CompositeKey('encounter_id', 'disappear_time')

to the Pokemon model class. This also causes the encounters with negative `time_till_hidden_ms` values to be stored, which may or may not be desirable. If it's not, we think this is best fixed in the parse_map() function.

Also see https://www.reddit.com/r/pokemongodev/comments/4vazmk/encounter_id_is_not_unique/

**Comment by favll** [comment]
Yep! Thank you for the kind reminder.

**Comment by nborrmann** [comment]
fixed
