### ISSUE TITLE
Slow down in response to throttling status code

### ISSUE THREAD

**Issue by pgodev** [favll/pogom#75]
With the ever-increasing rate limiting these days, it would be convenient to get a warning when the server is sending empty responses.

My current solution is to add

    if len(pokemons)+len(pokestops)+len(gyms)==0:
        log.error("Maybe we get throttled")

to parse_map() function, but I'm sure you guys can come up with something cleaner.

**Comment by favll** [comment]
The Pogo Api uses the status code 52 to notify clients that they need to slow down and that they are being throttled. We are going to add some kind of system to slow down our request rate in response to receiving this code.

**Comment by pgodev** [comment]
Nice solution; that's exactly why I said _I'm sure you guys can come up with something cleaner._

Some kind of warning to the terminal would still be useful though :-)
