### ISSUE TITLE
Use tejado/pgoapi as requirement instead of keeping a local copy

### ISSUE THREAD

**Issue by pgodev** [favll/pogom#76]
A quick diff between tejado's master and your `feature-multiple-accounts` branch shows mostly whitespace and import differences, and the PGoApiWorker class that was added to `pgoapi.py`. 

Maybe the threading code should go somewhere else, so you can remove the pgoapi directory and add tejado/pgoapi.git to requirements.txt. This would make for an even cleaner and smaller codebase, and easier fixes from upstream.

**Comment by favll** [comment]
We basically rebuilt pgoapi to be multithreaded and to use multiple accounts. I'm not entirely sure if it is possible to write a top-level api class without modifying a few things deep within pgoapi, however, I will take a look at it.

**Comment by pgodev** [comment]
The PokemonGo-Map people managed it (without too many changes) in their pgoapi-purge branch, and modrzew's pokeminer also uses multiple workers with the upstream pgoapi.

I'd be happy to give this a try, but I'd rather wait out the current API issue.

**Comment by nborrmann** [comment]
We did too many changes to use it as a dependency.
