### ISSUE TITLE
Oops! Something went wrong. This page didn't load Google Maps correctly. See the JavaScript console for technical details.

### ISSUE THREAD

**Issue by ithotline** [favll/pogom#77]
Could somebody tell me why im getting this? Scans seems to be done ok...?

**Comment by favll** [comment]
Due to API changes by Niantic the master branch is broken at the moment. We're releasing a new version today. Stay posted!

**Comment by ithotline** [comment]
Awesome... Thanks!

**Comment by momadness** [comment]
Getting same error - Staying tuned....
Kudos to the team!

**Comment by momadness** [comment]
Any news?

**Comment by favll** [comment]
Check the master branch!

**Comment by momadness** [comment]
I ran new installation - white screen when opening map after config.
started server on 127.0.0.1:5001 - "Oops" message reappered :(
