### ISSUE TITLE
what am i doing wrong?

### ISSUE THREAD

**Issue by geekabit** [favll/pogom#81]
so i got fresh vps ubuntu 16.04
i did all those steps:

1. sudo apt-get install libssl-dev libcurl4-openssl-dev python-dev
2. git clone https://github.com/favll/pogom.git
3. pip install -r requirements.txt
4. edit config.json with working logins and google api
5. python runserver.py -H <vps IP> -P <port>

and this is what i get:
2016-08-08 10:08:57,467 [   auth_ptc] [   INFO] PTC User Login for: [xxx]
2016-08-08 10:08:57,885 [   auth_ptc] [   INFO] PTC User Login successful.
2016-08-08 10:08:58,030 [       scan] [   INFO] Map Download failed. Trying agai                                                     n.

please explain what am i doing wrong

**Comment by favll** [comment]
You don't actually have to create config.json manually. You can delete it and start the server without it. This allows you to use the web interface for configuration. Have you tried this?

**Comment by geekabit** [comment]
@favll yup i saw web interface - nice feature :)
all informations that i provided config.json with was there when i logged in.

**Comment by favll** [comment]
Have you tried using different accounts? What hosting provider are you using for your VPS? Multiple hosting providers' IP ranges have been banned by Niantic.

**Comment by geekabit** [comment]
digitalocean /location:amsterdam
i have tried with 2 PTC accounts so far. ill try with new one and give you feedback

**Comment by favll** [comment]
Yeah, Digital Ocean's IPs have been banned. You sadly can't use them anymore :/
