### ISSUE TITLE
[Suggestion] option for each pokemon

### ISSUE THREAD

**Issue by EiTeR94** [favll/pogom#84]
can you add few option on the pop up of the pokemon, like delete if you already catch him

**Comment by nborrmann** [comment]
We now have an option to hide the pokemon from the label.
As for deleting a single pokemon, I don't see the point in that, not gonna add it.

**Comment by EiTeR94** [comment]
ofc, but if you catch this pokemon you will see him until the timer f de.
So you don't see the point in that, but it's usefull.
Hide pokemon will hide ALL the pokemon you entered...
