### ISSUE TITLE
[IMPROVEMENT] Add excude pokemon to config

### ISSUE THREAD

**Issue by stlmikey80** [favll/pogom#86]
Can you add exclude pokemon to config.. When i want to use ngrok to host outside, I get new link and i need to retype all those pokemon i dont want to see again.. 

Thanks

**Comment by nborrmann** [comment]
We save the excluded pokemon on the client side. So you need to hide them once on every device. This is not much of an issue imo.

Unless ngrok is changing urls all the time? 

Closing this for now.

**Comment by stlmikey80** [comment]
Yes everytime you relaunch ngrok you get a new link.. is there file edits i can do this manually then?  thanks
