### ISSUE TITLE
[Suggestion] Clusters

### ISSUE THREAD

**Issue by Lionir** [favll/pogom#89]
Group objects in clusters to reduce lag while moving around the map.

**Comment by nborrmann** [comment]
I really really hate the UX of those google maps clusters. And I didn't have much lag even with extremely many pokemon (before throttling was introduced).

**Comment by Lionir** [comment]
@nborrman I have a low end computer so the map often lags and stutters while there are many Pokemons. Could there be an option for it at the very least? It's quite frustrating to try to move the map and have it stutter a lot.
