### ISSUE TITLE
[Suggestion] Each Scan shows the account associated to it in Command-line.

### ISSUE THREAD

**Issue by Lionir** [favll/pogom#91]
This makes finding the account with a problem far far easier when using more accounts like I am.

**Comment by nborrmann** [comment]
Working on a fix to re-login the faulty account.

**Comment by Lionir** [comment]
@nbornmann Well, in my case, the account won't work on any scanning program. It never does for unknown reasons and I've just now found out which account it was but I think this should be implemented.

**Comment by Lionir** [comment]
@nborrmann Sorry, Just realized I misspelled your username :P

Please respond? xP
