### ISSUE TITLE
'int' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by tommiethecat** [favll/pogom#92]
Hey Guys,
Trying to get this working on a OSX, El Capitan. I believe all the dependencies are set. Any ideas what this could be? Null pointer in the python code?

Traceback (most recent call last):
  File "runserver.py", line 13, in <module>
    from pogom.app import Pogom
  File "/pogom-master/pogom/app.py", line 18, in <module>
    from .scan import ScanMetrics, Scanner
  File "/pogom-master/pogom/scan.py", line 16, in <module>
    from pgoapi import PGoApi
  File "/pogom-master/pogom/pgoapi/__init__.py", line 48, in <module>
    print int(protobuf_version[:1])
TypeError: 'int' object has no attribute '__getitem__'

**Comment by nborrmann** [comment]
Possibly fixed in the newest version.

It still won't work though. You seem to be missing the protobuf dependency. But you should get a different error message.

**Comment by nborrmann** [comment]
Closing this for now. Please comment if this is still an issue.

**Comment by tommiethecat** [comment]
Everything ran fine after later release and protobuff.  VC++ distro then just reran 
pip install -r requirements.txt

Running with 6 workers, 600m each typically runs under 6 minutes. No crashses.
Very good work.
